#!/usr/bin/env bash
#
# Dump the current contents of the 'lnu-timetable' database (data only, no
# schema) and overwrite src/main/resources/db/data.sql with it.
#
# Credentials/connection info are read from src/main/resources/application.properties
# (spring.r2dbc.url / spring.r2dbc.username / spring.r2dbc.password), so this
# stays in sync automatically if that file changes.
#
# Usage (run from anywhere, or from the "timetable" project root):
#   scripts/backup_data.sh
#
# Requires the PostgreSQL client tools (pg_dump) to be installed locally.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
PROPERTIES_FILE="$PROJECT_ROOT/src/main/resources/application.properties"
OUTPUT_FILE="$PROJECT_ROOT/src/main/resources/db/data.sql"

if ! command -v pg_dump >/dev/null 2>&1; then
    echo "Error: pg_dump not found. Install the PostgreSQL client tools first." >&2
    exit 1
fi

if [[ ! -f "$PROPERTIES_FILE" ]]; then
    echo "Error: properties file not found at $PROPERTIES_FILE" >&2
    exit 1
fi

# Pull a "key=value" line out of application.properties (ignores blank/# lines).
read_prop() {
    local key="$1"
    grep -E "^${key}=" "$PROPERTIES_FILE" | tail -n1 | cut -d'=' -f2- | tr -d '\r'
}

DB_URL="$(read_prop 'spring\.r2dbc\.url')"
DB_USER="$(read_prop 'spring\.r2dbc\.username')"
DB_PASSWORD="$(read_prop 'spring\.r2dbc\.password')"

if [[ -z "$DB_URL" ]]; then
    echo "Error: spring.r2dbc.url not found in $PROPERTIES_FILE" >&2
    exit 1
fi

# DB_URL looks like: r2dbc:postgresql://HOST:PORT/DBNAME
CONN="${DB_URL#r2dbc:postgresql://}"
DB_HOST_PORT="${CONN%%/*}"
DB_NAME="${CONN#*/}"
DB_HOST="${DB_HOST_PORT%%:*}"
DB_PORT="${DB_HOST_PORT##*:}"

echo "Backing up data from database '$DB_NAME' on $DB_HOST:$DB_PORT as user '$DB_USER'..."

export PGPASSWORD="$DB_PASSWORD"

{
    echo "-- Data-only backup of '$DB_NAME', generated by scripts/backup_data.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    pg_dump \
        --host="$DB_HOST" \
        --port="$DB_PORT" \
        --username="$DB_USER" \
        --dbname="$DB_NAME" \
        --data-only \
        --inserts \
        --column-inserts \
        --no-owner \
        --no-privileges \
        --disable-triggers
} > "$OUTPUT_FILE"

unset PGPASSWORD

echo "Done. Wrote $(wc -l < "$OUTPUT_FILE") lines to $OUTPUT_FILE"
