-- Seed data: real LNU faculties (from lnu.edu.ua/structure/faculties/) + synthetic scheduling data
INSERT INTO buildings (id, name, address, city, postal_code) VALUES
 (1,  'Корпус на вул. Грушевського',          'вул. Грушевського, 4',          'Львів', '79005'),
 (2,  'Корпус на вул. Дорошенка',              'вул. Дорошенка, 41',            'Львів', '79000'),
 (3,  'Корпус на просп. Свободи',              'проспект Свободи, 18',          'Львів', '79008'),
 (4,  'Корпус на вул. Драгоманова',            'вул. Драгоманова, 50',          'Львів', '79005'),
 (5,  'Корпус на вул. Чупринки',               'вул. Генерала Чупринки, 49',    'Львів', '79044'),
 (6,  'Університетський корпус',               'вул. Університетська, 1',       'Львів', '79000'),
 (7,  'Корпус на вул. Валовій',                'вул. Валова, 18',               'Львів', '79008'),
 (8,  'Корпус на вул. Січових Стрільців, 19',  'вул. Січових Стрільців, 19',    'Львів', '79000'),
 (9,  'Корпус на вул. Туган-Барановського',    'вул. Туган-Барановського, 7',   'Львів', '79000'),
 (10, 'Корпус на вул. Коперника',              'вул. Коперника, 3',             'Львів', '79000'),
 (11, 'Корпус на вул. Кирила і Мефодія, 8',   'вул. Кирила і Мефодія, 8',      'Львів', '79005'),
 (12, 'Корпус на вул. Кирила і Мефодія, 6',   'вул. Кирила і Мефодія, 6',      'Львів', '79005'),
 (13, 'Корпус на вул. Січових Стрільців, 14',  'вул. Січових Стрільців, 14',    'Львів', '79000');
SELECT setval('buildings_id_seq', 13);

-- IDs 1–2 kept as ФПМіІ and ММФ so synthetic scheduling data (departments/specialties/workloads) still references valid faculty_ids.
INSERT INTO faculties (id, name, abbreviation, email, phone, website, building_id) VALUES
 (1,  'Факультет прикладної математики та інформатики', 'ФПМіІ', 'ami@lnu.edu.ua',                   '(+38 032) 274-01-80; 239-41-86',       'https://ami.lnu.edu.ua',          6),
 (2,  'Механіко-математичний факультет',                'ММФ',   'dmmf@lnu.edu.ua',                  '(+38 032) 260-00-09; 239-41-74; 239-47-43', 'https://new.mmf.lnu.edu.ua',   6),
 (3,  'Біологічний факультет',                          'БФ',    'biolog@lnu.edu.ua',                '(+38 032) 274-03-72; 239-41-53',       'https://bioweb.lnu.edu.ua',       1),
 (4,  'Географічний факультет',                         'ГеогФ', 'geography.faculty@lnu.edu.ua',     '(+38 032) 239-46-46; 239-41-62',       'https://geography.lnu.edu.ua',    2),
 (5,  'Геологічний факультет',                          'ГеолФ', 'geology.faculty@lnu.edu.ua',       '(+38 032) 239-41-56',                  'https://geology.lnu.edu.ua',      1),
 (6,  'Економічний факультет',                          'ЕкФ',   'edean@lnu.edu.ua',                 '(+38 032) 239-41-68',                  'https://econom.lnu.edu.ua',       3),
 (7,  'Факультет електроніки та комп''ютерних технологій', 'ФЕКТ', 'electronics.faculty@lnu.edu.ua', '(+38 032) 261-14-91; 239-47-24; 239-41-82', 'https://electronics.lnu.edu.ua', 4),
 (8,  'Факультет журналістики',                         'ФЖ',    'journft@lnu.edu.ua',               '(+38 032) 239-47-51',                  'https://journ.lnu.edu.ua',        5),
 (9,  'Факультет іноземних мов',                        'ФІМ',   'lingua.faculty@lnu.edu.ua',        '(+38 032) 239-47-16',                  'https://lingua.lnu.edu.ua',       6),
 (10, 'Історичний факультет',                           'ІФ',    'clio@lnu.edu.ua',                  '(+38 032) 261-03-28',                  'https://clio.lnu.edu.ua',         6),
 (11, 'Факультет культури і мистецтв',                  'ФКМ',   'fkultart@lnu.edu.ua',              '(+38 032) 239-41-97',                  'https://kultart.lnu.edu.ua',      7),
 (12, 'Факультет міжнародних відносин',                 'ФМВ',   'intrel.faculty@lnu.edu.ua',        '(+38 032) 272-79-73; 239-44-20; 239-47-48', 'https://intrel.lnu.edu.ua',    8),
 (13, 'Факультет педагогічної освіти',                  'ФПО',   'pedagogy.faculty@lnu.edu.ua',      '(+38 032) 239-42-30',                  'https://pedagogy.lnu.edu.ua',     9),
 (14, 'Факультет управління фінансами та бізнесу',      'ФУФБ',  'financial.faculty@lnu.edu.ua',     '(+38 032) 235-64-50; 235-86-54',       'https://financial.lnu.edu.ua',    10),
 (15, 'Фізичний факультет',                             'ФзФ',   'physics.faculty@lnu.edu.ua',       '(+38 032) 239-41-16',                  'https://physics.lnu.edu.ua',      11),
 (16, 'Філологічний факультет',                         'ФлФ',   'philology.faculty@lnu.edu.ua',     '(+38 032) 255-41-33; 239-41-58; 239-41-88', 'https://philology.lnu.edu.ua', 6),
 (17, 'Філософський факультет',                         'ФсФ',   'dfilos@lnu.edu.ua',                '(+38 032) 239-45-79',                  'https://filos.lnu.edu.ua',        6),
 (18, 'Хімічний факультет',                             'ХФ',    'chemdek@lnu.edu.ua',               '(+38 032) 260-03-91; 239-45-10',       'https://chem.lnu.edu.ua',         12),
 (19, 'Юридичний факультет',                            'ЮФ',    'law.faculty@lnu.edu.ua',           '(+38 032) 239-41-02',                  'https://law.lnu.edu.ua',          13);
SELECT setval('faculties_id_seq', 19);
INSERT INTO departments (id, name, abbreviation, faculty_id) VALUES (1, 'Department 1', 'К1', 1),
 (2, 'Department 2', 'К2', 2),
 (3, 'Department 3', 'К3', 1),
 (4, 'Department 4', 'К4', 2);
SELECT setval('departments_id_seq', 4);
INSERT INTO specialties (id, code, name, degree, faculty_id) VALUES (1, '122', 'Computer Science', 'BACHELOR', 1),
 (2, '124', 'System Analysis', 'BACHELOR', 2),
 (3, '113', 'Applied Mathematics', 'BACHELOR', 1),
 (4, '121', 'Software Engineering', 'BACHELOR', 2);
SELECT setval('specialties_id_seq', 4);
INSERT INTO academic_groups (id, name, course_year, study_form, students_count, specialty_id) VALUES (1, 'Grp-01', 1, 'FULL_TIME', 20, 1),
                                                                                                     (2, 'Grp-02', 2, 'FULL_TIME', 21, 2),
                                                                                                     (3, 'Grp-03', 3, 'FULL_TIME', 22, 3),
                                                                                                     (4, 'Grp-04', 4, 'FULL_TIME', 23, 4),
                                                                                                     (5, 'Grp-05', 1, 'FULL_TIME', 24, 1),
                                                                                                     (6, 'Grp-06', 2, 'FULL_TIME', 25, 2),
                                                                                                     (7, 'Grp-07', 3, 'FULL_TIME', 26, 3),
                                                                                                     (8, 'Grp-08', 4, 'FULL_TIME', 27, 4),
                                                                                                     (9, 'Grp-09', 1, 'FULL_TIME', 28, 1),
                                                                                                     (10, 'Grp-10', 2, 'FULL_TIME', 29, 2),
                                                                                                     (11, 'Grp-11', 3, 'FULL_TIME', 30, 3),
                                                                                                     (12, 'Grp-12', 4, 'FULL_TIME', 20, 4),
                                                                                                     (13, 'Grp-13', 1, 'FULL_TIME', 21, 1),
                                                                                                     (14, 'Grp-14', 2, 'FULL_TIME', 22, 2),
                                                                                                     (15, 'Grp-15', 3, 'FULL_TIME', 23, 3),
                                                                                                     (16, 'Grp-16', 4, 'FULL_TIME', 24, 4),
                                                                                                     (17, 'Grp-17', 1, 'FULL_TIME', 25, 1),
                                                                                                     (18, 'Grp-18', 2, 'FULL_TIME', 26, 2),
                                                                                                     (19, 'Grp-19', 3, 'FULL_TIME', 27, 3),
                                                                                                     (20, 'Grp-20', 4, 'FULL_TIME', 28, 4),
                                                                                                     (21, 'Grp-21', 1, 'FULL_TIME', 29, 1),
                                                                                                     (22, 'Grp-22', 2, 'FULL_TIME', 30, 2),
                                                                                                     (23, 'Grp-23', 3, 'FULL_TIME', 20, 3),
                                                                                                     (24, 'Grp-24', 4, 'FULL_TIME', 21, 4),
                                                                                                     (25, 'Grp-25', 1, 'FULL_TIME', 22, 1),
                                                                                                     (26, 'Grp-26', 2, 'FULL_TIME', 23, 2),
                                                                                                     (27, 'Grp-27', 3, 'FULL_TIME', 24, 3),
                                                                                                     (28, 'Grp-28', 4, 'FULL_TIME', 25, 4),
                                                                                                     (29, 'Grp-29', 1, 'FULL_TIME', 26, 1),
                                                                                                     (30, 'Grp-30', 2, 'FULL_TIME', 27, 2),
                                                                                                     (31, 'Grp-31', 3, 'FULL_TIME', 28, 3),
                                                                                                     (32, 'Grp-32', 4, 'FULL_TIME', 29, 4),
                                                                                                     (33, 'Grp-33', 1, 'FULL_TIME', 30, 1),
                                                                                                     (34, 'Grp-34', 2, 'FULL_TIME', 20, 2),
                                                                                                     (35, 'Grp-35', 3, 'FULL_TIME', 21, 3),
                                                                                                     (36, 'Grp-36', 4, 'FULL_TIME', 22, 4),
                                                                                                     (37, 'Grp-37', 1, 'FULL_TIME', 23, 1),
                                                                                                     (38, 'Grp-38', 2, 'FULL_TIME', 24, 2),
                                                                                                     (39, 'Grp-39', 3, 'FULL_TIME', 25, 3),
                                                                                                     (40, 'Grp-40', 4, 'FULL_TIME', 26, 4);
SELECT setval('academic_groups_id_seq', 40);
INSERT INTO students (id, first_name, last_name, email, academic_group_id) VALUES (1, 'Іван', 'Іванчук', 'stud1@lnu.edu.ua', 1),
                                                                                  (2, 'Олена', 'Бондар', 'stud2@lnu.edu.ua', 2),
                                                                                  (3, 'Петро', 'Мельник', 'stud3@lnu.edu.ua', 3),
                                                                                  (4, 'Марія', 'Романюк', 'stud4@lnu.edu.ua', 4),
                                                                                  (5, 'Андрій', 'Ткаченко', 'stud5@lnu.edu.ua', 5),
                                                                                  (6, 'Софія', 'Лисенко', 'stud6@lnu.edu.ua', 6),
                                                                                  (7, 'Дмитро', 'Поліщук', 'stud7@lnu.edu.ua', 7),
                                                                                  (8, 'Ірина', 'Кравець', 'stud8@lnu.edu.ua', 8),
                                                                                  (9, 'Тарас', 'Гриценко', 'stud9@lnu.edu.ua', 9),
                                                                                  (10, 'Наталія', 'Савчук', 'stud10@lnu.edu.ua', 10),
                                                                                  (11, 'Іван', 'Бойко', 'stud11@lnu.edu.ua', 11),
                                                                                  (12, 'Олена', 'Марченко', 'stud12@lnu.edu.ua', 12),
                                                                                  (13, 'Петро', 'Гаврилюк', 'stud13@lnu.edu.ua', 13),
                                                                                  (14, 'Марія', 'Петренко', 'stud14@lnu.edu.ua', 14),
                                                                                  (15, 'Андрій', 'Коваленко', 'stud15@lnu.edu.ua', 15),
                                                                                  (16, 'Софія', 'Шевченко', 'stud16@lnu.edu.ua', 16),
                                                                                  (17, 'Дмитро', 'Іванчук', 'stud17@lnu.edu.ua', 17),
                                                                                  (18, 'Ірина', 'Бондар', 'stud18@lnu.edu.ua', 18),
                                                                                  (19, 'Тарас', 'Мельник', 'stud19@lnu.edu.ua', 19),
                                                                                  (20, 'Наталія', 'Романюк', 'stud20@lnu.edu.ua', 20),
                                                                                  (21, 'Іван', 'Ткаченко', 'stud21@lnu.edu.ua', 21),
                                                                                  (22, 'Олена', 'Лисенко', 'stud22@lnu.edu.ua', 22),
                                                                                  (23, 'Петро', 'Поліщук', 'stud23@lnu.edu.ua', 23),
                                                                                  (24, 'Марія', 'Кравець', 'stud24@lnu.edu.ua', 24),
                                                                                  (25, 'Андрій', 'Гриценко', 'stud25@lnu.edu.ua', 25),
                                                                                  (26, 'Софія', 'Савчук', 'stud26@lnu.edu.ua', 26),
                                                                                  (27, 'Дмитро', 'Бойко', 'stud27@lnu.edu.ua', 27),
                                                                                  (28, 'Ірина', 'Марченко', 'stud28@lnu.edu.ua', 28),
                                                                                  (29, 'Тарас', 'Гаврилюк', 'stud29@lnu.edu.ua', 29),
                                                                                  (30, 'Наталія', 'Петренко', 'stud30@lnu.edu.ua', 30),
                                                                                  (31, 'Іван', 'Коваленко', 'stud31@lnu.edu.ua', 31),
                                                                                  (32, 'Олена', 'Шевченко', 'stud32@lnu.edu.ua', 32),
                                                                                  (33, 'Петро', 'Іванчук', 'stud33@lnu.edu.ua', 33),
                                                                                  (34, 'Марія', 'Бондар', 'stud34@lnu.edu.ua', 34),
                                                                                  (35, 'Андрій', 'Мельник', 'stud35@lnu.edu.ua', 35),
                                                                                  (36, 'Софія', 'Романюк', 'stud36@lnu.edu.ua', 36),
                                                                                  (37, 'Дмитро', 'Ткаченко', 'stud37@lnu.edu.ua', 37),
                                                                                  (38, 'Ірина', 'Лисенко', 'stud38@lnu.edu.ua', 38),
                                                                                  (39, 'Тарас', 'Поліщук', 'stud39@lnu.edu.ua', 39),
                                                                                  (40, 'Наталія', 'Кравець', 'stud40@lnu.edu.ua', 40);
SELECT setval('students_id_seq', 40);
INSERT INTO combined_groups (id, name, purpose) VALUES (1, 'Combined-01', 'Elective audience'),
                                                       (2, 'Combined-02', 'Elective audience'),
                                                       (3, 'Combined-03', 'Elective audience'),
                                                       (4, 'Combined-04', 'Elective audience'),
                                                       (5, 'Combined-05', 'Elective audience'),
                                                       (6, 'Combined-06', 'Elective audience'),
                                                       (7, 'Combined-07', 'Elective audience'),
                                                       (8, 'Combined-08', 'Elective audience'),
                                                       (9, 'Combined-09', 'Elective audience'),
                                                       (10, 'Combined-10', 'Elective audience'),
                                                       (11, 'Combined-11', 'Elective audience'),
                                                       (12, 'Combined-12', 'Elective audience'),
                                                       (13, 'Combined-13', 'Elective audience'),
                                                       (14, 'Combined-14', 'Elective audience'),
                                                       (15, 'Combined-15', 'Elective audience'),
                                                       (16, 'Combined-16', 'Elective audience'),
                                                       (17, 'Combined-17', 'Elective audience'),
                                                       (18, 'Combined-18', 'Elective audience'),
                                                       (19, 'Combined-19', 'Elective audience'),
                                                       (20, 'Combined-20', 'Elective audience'),
                                                       (21, 'Combined-21', 'Elective audience'),
                                                       (22, 'Combined-22', 'Elective audience'),
                                                       (23, 'Combined-23', 'Elective audience'),
                                                       (24, 'Combined-24', 'Elective audience'),
                                                       (25, 'Combined-25', 'Elective audience'),
                                                       (26, 'Combined-26', 'Elective audience'),
                                                       (27, 'Combined-27', 'Elective audience'),
                                                       (28, 'Combined-28', 'Elective audience'),
                                                       (29, 'Combined-29', 'Elective audience'),
                                                       (30, 'Combined-30', 'Elective audience'),
                                                       (31, 'Combined-31', 'Elective audience'),
                                                       (32, 'Combined-32', 'Elective audience'),
                                                       (33, 'Combined-33', 'Elective audience'),
                                                       (34, 'Combined-34', 'Elective audience'),
                                                       (35, 'Combined-35', 'Elective audience'),
                                                       (36, 'Combined-36', 'Elective audience'),
                                                       (37, 'Combined-37', 'Elective audience'),
                                                       (38, 'Combined-38', 'Elective audience'),
                                                       (39, 'Combined-39', 'Elective audience'),
                                                       (40, 'Combined-40', 'Elective audience'),
                                                       (41, 'Combined-41', 'Elective audience'),
                                                       (42, 'Combined-42', 'Elective audience'),
                                                       (43, 'Combined-43', 'Elective audience'),
                                                       (44, 'Combined-44', 'Elective audience'),
                                                       (45, 'Combined-45', 'Elective audience'),
                                                       (46, 'Combined-46', 'Elective audience'),
                                                       (47, 'Combined-47', 'Elective audience'),
                                                       (48, 'Combined-48', 'Elective audience'),
                                                       (49, 'Combined-49', 'Elective audience'),
                                                       (50, 'Combined-50', 'Elective audience'),
                                                       (51, 'Combined-51', 'Elective audience'),
                                                       (52, 'Combined-52', 'Elective audience'),
                                                       (53, 'Combined-53', 'Elective audience'),
                                                       (54, 'Combined-54', 'Elective audience'),
                                                       (55, 'Combined-55', 'Elective audience'),
                                                       (56, 'Combined-56', 'Elective audience'),
                                                       (57, 'Combined-57', 'Elective audience'),
                                                       (58, 'Combined-58', 'Elective audience'),
                                                       (59, 'Combined-59', 'Elective audience'),
                                                       (60, 'Combined-60', 'Elective audience'),
                                                       (61, 'Combined-61', 'Elective audience'),
                                                       (62, 'Combined-62', 'Elective audience'),
                                                       (63, 'Combined-63', 'Elective audience'),
                                                       (64, 'Combined-64', 'Elective audience'),
                                                       (65, 'Combined-65', 'Elective audience'),
                                                       (66, 'Combined-66', 'Elective audience'),
                                                       (67, 'Combined-67', 'Elective audience'),
                                                       (68, 'Combined-68', 'Elective audience'),
                                                       (69, 'Combined-69', 'Elective audience'),
                                                       (70, 'Combined-70', 'Elective audience'),
                                                       (71, 'Combined-71', 'Elective audience'),
                                                       (72, 'Combined-72', 'Elective audience'),
                                                       (73, 'Combined-73', 'Elective audience'),
                                                       (74, 'Combined-74', 'Elective audience'),
                                                       (75, 'Combined-75', 'Elective audience'),
                                                       (76, 'Combined-76', 'Elective audience'),
                                                       (77, 'Combined-77', 'Elective audience'),
                                                       (78, 'Combined-78', 'Elective audience'),
                                                       (79, 'Combined-79', 'Elective audience'),
                                                       (80, 'Combined-80', 'Elective audience'),
                                                       (81, 'Combined-81', 'Elective audience'),
                                                       (82, 'Combined-82', 'Elective audience'),
                                                       (83, 'Combined-83', 'Elective audience'),
                                                       (84, 'Combined-84', 'Elective audience'),
                                                       (85, 'Combined-85', 'Elective audience'),
                                                       (86, 'Combined-86', 'Elective audience'),
                                                       (87, 'Combined-87', 'Elective audience'),
                                                       (88, 'Combined-88', 'Elective audience'),
                                                       (89, 'Combined-89', 'Elective audience'),
                                                       (90, 'Combined-90', 'Elective audience'),
                                                       (91, 'Combined-91', 'Elective audience'),
                                                       (92, 'Combined-92', 'Elective audience'),
                                                       (93, 'Combined-93', 'Elective audience'),
                                                       (94, 'Combined-94', 'Elective audience'),
                                                       (95, 'Combined-95', 'Elective audience'),
                                                       (96, 'Combined-96', 'Elective audience'),
                                                       (97, 'Combined-97', 'Elective audience'),
                                                       (98, 'Combined-98', 'Elective audience'),
                                                       (99, 'Combined-99', 'Elective audience'),
                                                       (100, 'Combined-100', 'Elective audience'),
                                                       (101, 'Combined-101', 'Elective audience'),
                                                       (102, 'Combined-102', 'Elective audience'),
                                                       (103, 'Combined-103', 'Elective audience'),
                                                       (104, 'Combined-104', 'Elective audience'),
                                                       (105, 'Combined-105', 'Elective audience'),
                                                       (106, 'Combined-106', 'Elective audience'),
                                                       (107, 'Combined-107', 'Elective audience'),
                                                       (108, 'Combined-108', 'Elective audience'),
                                                       (109, 'Combined-109', 'Elective audience'),
                                                       (110, 'Combined-110', 'Elective audience'),
                                                       (111, 'Combined-111', 'Elective audience'),
                                                       (112, 'Combined-112', 'Elective audience'),
                                                       (113, 'Combined-113', 'Elective audience'),
                                                       (114, 'Combined-114', 'Elective audience'),
                                                       (115, 'Combined-115', 'Elective audience'),
                                                       (116, 'Combined-116', 'Elective audience'),
                                                       (117, 'Combined-117', 'Elective audience'),
                                                       (118, 'Combined-118', 'Elective audience'),
                                                       (119, 'Combined-119', 'Elective audience'),
                                                       (120, 'Combined-120', 'Elective audience'),
                                                       (121, 'Combined-121', 'Elective audience'),
                                                       (122, 'Combined-122', 'Elective audience'),
                                                       (123, 'Combined-123', 'Elective audience'),
                                                       (124, 'Combined-124', 'Elective audience'),
                                                       (125, 'Combined-125', 'Elective audience'),
                                                       (126, 'Combined-126', 'Elective audience'),
                                                       (127, 'Combined-127', 'Elective audience'),
                                                       (128, 'Combined-128', 'Elective audience'),
                                                       (129, 'Combined-129', 'Elective audience'),
                                                       (130, 'Combined-130', 'Elective audience'),
                                                       (131, 'Combined-131', 'Elective audience'),
                                                       (132, 'Combined-132', 'Elective audience'),
                                                       (133, 'Combined-133', 'Elective audience'),
                                                       (134, 'Combined-134', 'Elective audience'),
                                                       (135, 'Combined-135', 'Elective audience'),
                                                       (136, 'Combined-136', 'Elective audience'),
                                                       (137, 'Combined-137', 'Elective audience'),
                                                       (138, 'Combined-138', 'Elective audience'),
                                                       (139, 'Combined-139', 'Elective audience'),
                                                       (140, 'Combined-140', 'Elective audience'),
                                                       (141, 'Combined-141', 'Elective audience'),
                                                       (142, 'Combined-142', 'Elective audience'),
                                                       (143, 'Combined-143', 'Elective audience'),
                                                       (144, 'Combined-144', 'Elective audience'),
                                                       (145, 'Combined-145', 'Elective audience'),
                                                       (146, 'Combined-146', 'Elective audience'),
                                                       (147, 'Combined-147', 'Elective audience'),
                                                       (148, 'Combined-148', 'Elective audience'),
                                                       (149, 'Combined-149', 'Elective audience'),
                                                       (150, 'Combined-150', 'Elective audience'),
                                                       (151, 'Combined-151', 'Elective audience'),
                                                       (152, 'Combined-152', 'Elective audience'),
                                                       (153, 'Combined-153', 'Elective audience'),
                                                       (154, 'Combined-154', 'Elective audience'),
                                                       (155, 'Combined-155', 'Elective audience'),
                                                       (156, 'Combined-156', 'Elective audience'),
                                                       (157, 'Combined-157', 'Elective audience'),
                                                       (158, 'Combined-158', 'Elective audience'),
                                                       (159, 'Combined-159', 'Elective audience'),
                                                       (160, 'Combined-160', 'Elective audience'),
                                                       (161, 'Combined-161', 'Elective audience'),
                                                       (162, 'Combined-162', 'Elective audience'),
                                                       (163, 'Combined-163', 'Elective audience'),
                                                       (164, 'Combined-164', 'Elective audience'),
                                                       (165, 'Combined-165', 'Elective audience'),
                                                       (166, 'Combined-166', 'Elective audience'),
                                                       (167, 'Combined-167', 'Elective audience'),
                                                       (168, 'Combined-168', 'Elective audience'),
                                                       (169, 'Combined-169', 'Elective audience'),
                                                       (170, 'Combined-170', 'Elective audience'),
                                                       (171, 'Combined-171', 'Elective audience'),
                                                       (172, 'Combined-172', 'Elective audience'),
                                                       (173, 'Combined-173', 'Elective audience'),
                                                       (174, 'Combined-174', 'Elective audience'),
                                                       (175, 'Combined-175', 'Elective audience'),
                                                       (176, 'Combined-176', 'Elective audience'),
                                                       (177, 'Combined-177', 'Elective audience'),
                                                       (178, 'Combined-178', 'Elective audience'),
                                                       (179, 'Combined-179', 'Elective audience'),
                                                       (180, 'Combined-180', 'Elective audience'),
                                                       (181, 'Combined-181', 'Elective audience'),
                                                       (182, 'Combined-182', 'Elective audience'),
                                                       (183, 'Combined-183', 'Elective audience'),
                                                       (184, 'Combined-184', 'Elective audience'),
                                                       (185, 'Combined-185', 'Elective audience'),
                                                       (186, 'Combined-186', 'Elective audience'),
                                                       (187, 'Combined-187', 'Elective audience'),
                                                       (188, 'Combined-188', 'Elective audience'),
                                                       (189, 'Combined-189', 'Elective audience'),
                                                       (190, 'Combined-190', 'Elective audience'),
                                                       (191, 'Combined-191', 'Elective audience'),
                                                       (192, 'Combined-192', 'Elective audience'),
                                                       (193, 'Combined-193', 'Elective audience'),
                                                       (194, 'Combined-194', 'Elective audience'),
                                                       (195, 'Combined-195', 'Elective audience'),
                                                       (196, 'Combined-196', 'Elective audience'),
                                                       (197, 'Combined-197', 'Elective audience'),
                                                       (198, 'Combined-198', 'Elective audience'),
                                                       (199, 'Combined-199', 'Elective audience'),
                                                       (200, 'Combined-200', 'Elective audience'),
                                                       (201, 'Combined-201', 'Elective audience'),
                                                       (202, 'Combined-202', 'Elective audience'),
                                                       (203, 'Combined-203', 'Elective audience'),
                                                       (204, 'Combined-204', 'Elective audience'),
                                                       (205, 'Combined-205', 'Elective audience'),
                                                       (206, 'Combined-206', 'Elective audience'),
                                                       (207, 'Combined-207', 'Elective audience'),
                                                       (208, 'Combined-208', 'Elective audience'),
                                                       (209, 'Combined-209', 'Elective audience'),
                                                       (210, 'Combined-210', 'Elective audience');
SELECT setval('combined_groups_id_seq', 210);
INSERT INTO combined_group_academic_groups (combined_group_id, academic_group_id) VALUES (1, 20),
                                                                                         (1, 23),
                                                                                         (2, 15),
                                                                                         (2, 20),
                                                                                         (3, 20),
                                                                                         (3, 32),
                                                                                         (4, 25),
                                                                                         (4, 33),
                                                                                         (5, 3),
                                                                                         (5, 10),
                                                                                         (6, 3),
                                                                                         (6, 28),
                                                                                         (7, 23),
                                                                                         (7, 40),
                                                                                         (8, 1),
                                                                                         (8, 19),
                                                                                         (8, 34),
                                                                                         (9, 3),
                                                                                         (9, 13),
                                                                                         (9, 18),
                                                                                         (10, 13),
                                                                                         (10, 25),
                                                                                         (10, 32),
                                                                                         (11, 5),
                                                                                         (11, 7),
                                                                                         (11, 38),
                                                                                         (12, 10),
                                                                                         (12, 16),
                                                                                         (13, 9),
                                                                                         (13, 27),
                                                                                         (13, 36),
                                                                                         (14, 12),
                                                                                         (14, 31),
                                                                                         (15, 7),
                                                                                         (15, 22),
                                                                                         (16, 9),
                                                                                         (16, 37),
                                                                                         (17, 22),
                                                                                         (17, 29),
                                                                                         (17, 32),
                                                                                         (18, 16),
                                                                                         (18, 21),
                                                                                         (18, 33),
                                                                                         (19, 11),
                                                                                         (19, 36),
                                                                                         (20, 11),
                                                                                         (20, 37),
                                                                                         (20, 40),
                                                                                         (21, 2),
                                                                                         (21, 15),
                                                                                         (22, 12),
                                                                                         (22, 21),
                                                                                         (22, 36),
                                                                                         (23, 12),
                                                                                         (23, 34),
                                                                                         (24, 26),
                                                                                         (24, 29),
                                                                                         (25, 8),
                                                                                         (25, 17),
                                                                                         (26, 7),
                                                                                         (26, 14),
                                                                                         (26, 26),
                                                                                         (27, 24),
                                                                                         (27, 26),
                                                                                         (28, 1),
                                                                                         (28, 35),
                                                                                         (29, 4),
                                                                                         (29, 39),
                                                                                         (30, 15),
                                                                                         (30, 27),
                                                                                         (30, 39),
                                                                                         (31, 10),
                                                                                         (31, 12),
                                                                                         (32, 1),
                                                                                         (32, 14),
                                                                                         (32, 39),
                                                                                         (33, 6),
                                                                                         (33, 11),
                                                                                         (33, 40),
                                                                                         (34, 9),
                                                                                         (34, 39),
                                                                                         (35, 6),
                                                                                         (35, 7),
                                                                                         (35, 19),
                                                                                         (36, 11),
                                                                                         (36, 24),
                                                                                         (37, 13),
                                                                                         (37, 28),
                                                                                         (37, 40),
                                                                                         (38, 33),
                                                                                         (38, 35),
                                                                                         (39, 14),
                                                                                         (39, 22),
                                                                                         (39, 30),
                                                                                         (40, 29),
                                                                                         (40, 37),
                                                                                         (41, 16),
                                                                                         (41, 34),
                                                                                         (42, 19),
                                                                                         (42, 33),
                                                                                         (43, 28),
                                                                                         (43, 32),
                                                                                         (44, 8),
                                                                                         (44, 17),
                                                                                         (44, 25),
                                                                                         (45, 3),
                                                                                         (45, 5),
                                                                                         (45, 9),
                                                                                         (46, 7),
                                                                                         (46, 36),
                                                                                         (46, 38),
                                                                                         (47, 4),
                                                                                         (47, 20),
                                                                                         (48, 17),
                                                                                         (48, 27),
                                                                                         (49, 5),
                                                                                         (49, 22),
                                                                                         (49, 36),
                                                                                         (50, 26),
                                                                                         (50, 39),
                                                                                         (51, 26),
                                                                                         (51, 33),
                                                                                         (52, 16),
                                                                                         (52, 28),
                                                                                         (52, 36),
                                                                                         (53, 3),
                                                                                         (53, 15),
                                                                                         (53, 18),
                                                                                         (54, 19),
                                                                                         (54, 25),
                                                                                         (55, 4),
                                                                                         (55, 38),
                                                                                         (56, 18),
                                                                                         (56, 40),
                                                                                         (57, 1),
                                                                                         (57, 18),
                                                                                         (58, 21),
                                                                                         (58, 34),
                                                                                         (59, 8),
                                                                                         (59, 30),
                                                                                         (60, 10),
                                                                                         (60, 23),
                                                                                         (60, 37),
                                                                                         (61, 4),
                                                                                         (61, 29),
                                                                                         (62, 10),
                                                                                         (62, 22),
                                                                                         (62, 26),
                                                                                         (63, 6),
                                                                                         (63, 11),
                                                                                         (64, 7),
                                                                                         (64, 23),
                                                                                         (64, 34),
                                                                                         (65, 6),
                                                                                         (65, 18),
                                                                                         (65, 38),
                                                                                         (66, 4),
                                                                                         (66, 13),
                                                                                         (66, 36),
                                                                                         (67, 21),
                                                                                         (67, 28),
                                                                                         (68, 22),
                                                                                         (68, 40),
                                                                                         (69, 3),
                                                                                         (69, 10),
                                                                                         (69, 14),
                                                                                         (70, 5),
                                                                                         (70, 8),
                                                                                         (70, 19),
                                                                                         (71, 9),
                                                                                         (71, 12),
                                                                                         (72, 6),
                                                                                         (72, 17),
                                                                                         (72, 24),
                                                                                         (73, 24),
                                                                                         (73, 39),
                                                                                         (74, 9),
                                                                                         (74, 25),
                                                                                         (75, 13),
                                                                                         (75, 38),
                                                                                         (76, 2),
                                                                                         (76, 28),
                                                                                         (77, 21),
                                                                                         (77, 30),
                                                                                         (78, 27),
                                                                                         (78, 31),
                                                                                         (78, 34),
                                                                                         (79, 9),
                                                                                         (79, 23),
                                                                                         (80, 14),
                                                                                         (80, 15),
                                                                                         (81, 4),
                                                                                         (81, 5),
                                                                                         (82, 24),
                                                                                         (82, 35),
                                                                                         (83, 16),
                                                                                         (83, 29),
                                                                                         (83, 37),
                                                                                         (84, 3),
                                                                                         (84, 30),
                                                                                         (85, 18),
                                                                                         (85, 31),
                                                                                         (85, 36),
                                                                                         (86, 17),
                                                                                         (86, 22),
                                                                                         (87, 1),
                                                                                         (87, 20),
                                                                                         (88, 12),
                                                                                         (88, 37),
                                                                                         (89, 8),
                                                                                         (89, 25),
                                                                                         (89, 35),
                                                                                         (90, 10),
                                                                                         (90, 17),
                                                                                         (91, 11),
                                                                                         (91, 15),
                                                                                         (91, 36),
                                                                                         (92, 19),
                                                                                         (92, 21),
                                                                                         (92, 33),
                                                                                         (93, 26),
                                                                                         (93, 28),
                                                                                         (93, 32),
                                                                                         (94, 25),
                                                                                         (94, 27),
                                                                                         (95, 11),
                                                                                         (95, 29),
                                                                                         (95, 39),
                                                                                         (96, 27),
                                                                                         (96, 31),
                                                                                         (97, 14),
                                                                                         (97, 18),
                                                                                         (97, 20),
                                                                                         (98, 6),
                                                                                         (98, 21),
                                                                                         (98, 38),
                                                                                         (99, 19),
                                                                                         (99, 24),
                                                                                         (99, 25),
                                                                                         (100, 31),
                                                                                         (100, 33),
                                                                                         (101, 4),
                                                                                         (101, 15),
                                                                                         (101, 26),
                                                                                         (102, 9),
                                                                                         (102, 11),
                                                                                         (102, 30),
                                                                                         (103, 2),
                                                                                         (103, 14),
                                                                                         (103, 33),
                                                                                         (104, 7),
                                                                                         (104, 21),
                                                                                         (105, 18),
                                                                                         (105, 28),
                                                                                         (105, 31),
                                                                                         (106, 1),
                                                                                         (106, 24),
                                                                                         (106, 25),
                                                                                         (107, 6),
                                                                                         (107, 35),
                                                                                         (108, 7),
                                                                                         (108, 29),
                                                                                         (109, 19),
                                                                                         (109, 23),
                                                                                         (109, 28),
                                                                                         (110, 8),
                                                                                         (110, 37),
                                                                                         (111, 1),
                                                                                         (111, 11),
                                                                                         (111, 34),
                                                                                         (112, 3),
                                                                                         (112, 22),
                                                                                         (113, 1),
                                                                                         (113, 4),
                                                                                         (114, 9),
                                                                                         (114, 13),
                                                                                         (114, 26),
                                                                                         (115, 3),
                                                                                         (115, 16),
                                                                                         (115, 35),
                                                                                         (116, 23),
                                                                                         (116, 34),
                                                                                         (117, 7),
                                                                                         (117, 14),
                                                                                         (117, 20),
                                                                                         (118, 20),
                                                                                         (118, 39),
                                                                                         (119, 9),
                                                                                         (119, 40),
                                                                                         (120, 2),
                                                                                         (120, 10),
                                                                                         (121, 5),
                                                                                         (121, 17),
                                                                                         (121, 34),
                                                                                         (122, 15),
                                                                                         (122, 18),
                                                                                         (123, 21),
                                                                                         (123, 27),
                                                                                         (124, 6),
                                                                                         (124, 37),
                                                                                         (125, 16),
                                                                                         (125, 28),
                                                                                         (126, 10),
                                                                                         (126, 38),
                                                                                         (127, 15),
                                                                                         (127, 30),
                                                                                         (128, 11),
                                                                                         (128, 31),
                                                                                         (129, 10),
                                                                                         (129, 19),
                                                                                         (129, 34),
                                                                                         (130, 13),
                                                                                         (130, 21),
                                                                                         (130, 38),
                                                                                         (131, 1),
                                                                                         (131, 26),
                                                                                         (132, 22),
                                                                                         (132, 32),
                                                                                         (133, 22),
                                                                                         (133, 29),
                                                                                         (134, 20),
                                                                                         (134, 21),
                                                                                         (135, 2),
                                                                                         (135, 36),
                                                                                         (136, 5),
                                                                                         (136, 21),
                                                                                         (137, 24),
                                                                                         (137, 32),
                                                                                         (138, 28),
                                                                                         (138, 29),
                                                                                         (139, 16),
                                                                                         (139, 38),
                                                                                         (140, 12),
                                                                                         (140, 18),
                                                                                         (141, 1),
                                                                                         (141, 5),
                                                                                         (141, 22),
                                                                                         (142, 14),
                                                                                         (142, 23),
                                                                                         (143, 7),
                                                                                         (143, 11),
                                                                                         (143, 26),
                                                                                         (144, 19),
                                                                                         (144, 23),
                                                                                         (144, 36),
                                                                                         (145, 3),
                                                                                         (145, 6),
                                                                                         (145, 31),
                                                                                         (146, 10),
                                                                                         (146, 39),
                                                                                         (147, 11),
                                                                                         (147, 14),
                                                                                         (148, 21),
                                                                                         (148, 32),
                                                                                         (148, 38),
                                                                                         (149, 4),
                                                                                         (149, 35),
                                                                                         (150, 37),
                                                                                         (150, 39),
                                                                                         (151, 1),
                                                                                         (151, 28),
                                                                                         (152, 12),
                                                                                         (152, 21),
                                                                                         (153, 4),
                                                                                         (153, 8),
                                                                                         (153, 27),
                                                                                         (154, 6),
                                                                                         (154, 16),
                                                                                         (155, 13),
                                                                                         (155, 36),
                                                                                         (156, 11),
                                                                                         (156, 19),
                                                                                         (157, 2),
                                                                                         (157, 32),
                                                                                         (158, 20),
                                                                                         (158, 28),
                                                                                         (159, 4),
                                                                                         (159, 30),
                                                                                         (160, 1),
                                                                                         (160, 22),
                                                                                         (161, 17),
                                                                                         (161, 20),
                                                                                         (161, 29),
                                                                                         (162, 7),
                                                                                         (162, 13),
                                                                                         (162, 20),
                                                                                         (163, 3),
                                                                                         (163, 18),
                                                                                         (163, 31),
                                                                                         (164, 35),
                                                                                         (164, 36),
                                                                                         (164, 39),
                                                                                         (165, 13),
                                                                                         (165, 22),
                                                                                         (166, 16),
                                                                                         (166, 27),
                                                                                         (167, 7),
                                                                                         (167, 17),
                                                                                         (168, 5),
                                                                                         (168, 10),
                                                                                         (168, 33),
                                                                                         (169, 22),
                                                                                         (169, 24),
                                                                                         (169, 34),
                                                                                         (170, 2),
                                                                                         (170, 11),
                                                                                         (171, 33),
                                                                                         (171, 37),
                                                                                         (172, 6),
                                                                                         (172, 12),
                                                                                         (172, 21),
                                                                                         (173, 9),
                                                                                         (173, 18),
                                                                                         (173, 38),
                                                                                         (174, 14),
                                                                                         (174, 27),
                                                                                         (175, 12),
                                                                                         (175, 20),
                                                                                         (176, 10),
                                                                                         (176, 29),
                                                                                         (177, 10),
                                                                                         (177, 18),
                                                                                         (178, 15),
                                                                                         (178, 39),
                                                                                         (179, 12),
                                                                                         (179, 25),
                                                                                         (180, 15),
                                                                                         (180, 21),
                                                                                         (180, 33),
                                                                                         (181, 4),
                                                                                         (181, 11),
                                                                                         (182, 10),
                                                                                         (182, 13),
                                                                                         (182, 17),
                                                                                         (183, 32),
                                                                                         (183, 34),
                                                                                         (184, 13),
                                                                                         (184, 25),
                                                                                         (184, 39),
                                                                                         (185, 30),
                                                                                         (185, 31),
                                                                                         (186, 9),
                                                                                         (186, 32),
                                                                                         (187, 17),
                                                                                         (187, 38),
                                                                                         (188, 18),
                                                                                         (188, 24),
                                                                                         (189, 5),
                                                                                         (189, 12),
                                                                                         (189, 19),
                                                                                         (190, 8),
                                                                                         (190, 31),
                                                                                         (191, 1),
                                                                                         (191, 11),
                                                                                         (192, 5),
                                                                                         (192, 7),
                                                                                         (193, 24),
                                                                                         (193, 37),
                                                                                         (194, 11),
                                                                                         (194, 15),
                                                                                         (194, 23),
                                                                                         (195, 23),
                                                                                         (195, 37),
                                                                                         (195, 40),
                                                                                         (196, 6),
                                                                                         (196, 34),
                                                                                         (197, 9),
                                                                                         (197, 19),
                                                                                         (198, 2),
                                                                                         (198, 7),
                                                                                         (199, 23),
                                                                                         (199, 38),
                                                                                         (200, 4),
                                                                                         (200, 33),
                                                                                         (201, 8),
                                                                                         (201, 13),
                                                                                         (202, 17),
                                                                                         (202, 39),
                                                                                         (203, 14),
                                                                                         (203, 18),
                                                                                         (203, 31),
                                                                                         (204, 16),
                                                                                         (204, 36),
                                                                                         (205, 6),
                                                                                         (205, 20),
                                                                                         (206, 26),
                                                                                         (206, 36),
                                                                                         (207, 6),
                                                                                         (207, 21),
                                                                                         (207, 27),
                                                                                         (208, 15),
                                                                                         (208, 20),
                                                                                         (208, 29),
                                                                                         (209, 7),
                                                                                         (209, 19),
                                                                                         (210, 3),
                                                                                         (210, 38);
INSERT INTO courses (id, name, department_id) VALUES
 (1, 'Discipline 01', 1),
 (2, 'Discipline 02', 2),
 (3, 'Discipline 03', 3),
 (4, 'Discipline 04', 4),
 (5, 'Discipline 05', 1),
 (6, 'Discipline 06', 2),
 (7, 'Discipline 07', 3),
 (8, 'Discipline 08', 4),
 (9, 'Discipline 09', 1),
 (10, 'Discipline 10', 2),
 (11, 'Discipline 11', 3),
 (12, 'Discipline 12', 4),
 (13, 'Discipline 13', 1),
 (14, 'Discipline 14', 2),
 (15, 'Discipline 15', 3),
 (16, 'Discipline 16', 4),
 (17, 'Discipline 17', 1),
 (18, 'Discipline 18', 2),
 (19, 'Discipline 19', 3),
 (20, 'Discipline 20', 4),
 (21, 'Discipline 21', 1),
 (22, 'Discipline 22', 2),
 (23, 'Discipline 23', 3),
 (24, 'Discipline 24', 4);
SELECT setval('courses_id_seq', 24);
INSERT INTO curricula (id, specialty_id) VALUES (1, 1), (2, 2), (3, 3), (4, 4);
SELECT setval('curricula_id_seq', 4);
INSERT INTO curriculum_items (id, semester, control_form, ects_credits, curriculum_id, course_id) VALUES
 (1, 1, 'EXAM',          6, 1, 1),
 (2, 2, 'CREDIT',        4, 2, 2),
 (3, 3, 'EXAM',          5, 3, 3),
 (4, 4, 'GRADED_CREDIT', 4, 4, 4),
 (5, 5, 'EXAM',          6, 1, 5),
 (6, 6, 'CREDIT',        4, 2, 6),
 (7, 1, 'EXAM',          5, 3, 7),
 (8, 2, 'GRADED_CREDIT', 4, 4, 8);
SELECT setval('curriculum_items_id_seq', 8);
-- Hours per class type for each curriculum item (LECTURE + LAB/PRACTICAL pairs)
INSERT INTO curriculum_item_hours (id, hour_type, hours, curriculum_item_id) VALUES
 (1,  'LECTURE',   32, 1),  (2,  'LAB',       16, 1),
 (3,  'LECTURE',   32, 2),  (4,  'PRACTICAL',  16, 2),
 (5,  'LECTURE',   32, 3),  (6,  'LAB',        16, 3),
 (7,  'LECTURE',   32, 4),  (8,  'PRACTICAL',  16, 4),
 (9,  'LECTURE',   32, 5),  (10, 'LAB',        16, 5),
 (11, 'LECTURE',   32, 6),  (12, 'PRACTICAL',  16, 6),
 (13, 'LECTURE',   32, 7),  (14, 'LAB',        16, 7),
 (15, 'LECTURE',   32, 8),  (16, 'PRACTICAL',  16, 8);
SELECT setval('curriculum_item_hours_id_seq', 16);
-- Each working_curriculum_item corresponds to one curriculum_item_hours row
INSERT INTO working_curriculum_items (id, lecturer_count, teaching_format, curriculum_item_hours_id, department_id) VALUES
 (1,  1, 'SEPARATELY', 1,  1),   -- lecture for ci=1
 (2,  1, 'SEPARATELY', 2,  1),   -- lab for ci=1
 (3,  1, 'SEPARATELY', 3,  2),   -- lecture for ci=2
 (4,  1, 'SEPARATELY', 4,  2),   -- practical for ci=2
 (5,  1, 'SEPARATELY', 5,  3),   -- lecture for ci=3
 (6,  1, 'SEPARATELY', 6,  3),   -- lab for ci=3
 (7,  1, 'SEPARATELY', 7,  4),   -- lecture for ci=4
 (8,  1, 'SEPARATELY', 8,  4),   -- practical for ci=4
 (9,  1, 'TOGETHER',   9,  1),   -- lecture for ci=5 (combined)
 (10, 1, 'SEPARATELY', 10, 1),   -- lab for ci=5
 (11, 1, 'TOGETHER',   11, 2),   -- lecture for ci=6 (combined)
 (12, 1, 'SEPARATELY', 12, 2),   -- practical for ci=6
 (13, 1, 'SEPARATELY', 13, 3),   -- lecture for ci=7
 (14, 1, 'SEPARATELY', 14, 3),   -- lab for ci=7
 (15, 1, 'SEPARATELY', 15, 4),   -- lecture for ci=8
 (16, 1, 'SEPARATELY', 16, 4);   -- practical for ci=8
SELECT setval('working_curriculum_items_id_seq', 16);
INSERT INTO working_curriculum_item_groups (working_curriculum_item_id, academic_group_id) VALUES
 (1, 1), (1, 5),
 (2, 1), (2, 5),
 (3, 2), (3, 6),
 (4, 2), (4, 6),
 (5, 3), (5, 7),
 (6, 3), (6, 7),
 (7, 4), (7, 8),
 (8, 4), (8, 8),
 (9, 9), (9, 13),
 (10, 9), (10, 13),
 (11, 10), (11, 14),
 (12, 10), (12, 14),
 (13, 11), (13, 15),
 (14, 11), (14, 15),
 (15, 12), (15, 16),
 (16, 12), (16, 16);
-- Academic degrees per Law on Higher Education of Ukraine (Art. 5)
-- level: 1 = Кандидат наук (transitional), 2 = Доктор філософії (PhD), 3 = Доктор наук
INSERT INTO academic_degrees (id, name, abbreviation, level) VALUES
 (1, 'Кандидат наук',     'к.н.',  1),
 (2, 'Доктор філософії',  'PhD',   2),
 (3, 'Доктор наук',       'д-р н.',3);
SELECT setval('academic_degrees_id_seq', 3);

-- academic_degree_id: NULL=no degree, 1=к.н., 2=PhD, 3=д-р н.
-- ASSISTANT/TEACHER → no degree (NULL); SENIOR_LECTURER → к.н.(1); DOCENT → PhD(2); PROFESSOR → д-р н.(3)
INSERT INTO lecturers (id, first_name, last_name, email, position, academic_degree_id, department_id) VALUES
 (1,  'Іван',    'Петренко',  'lect1@lnu.edu.ua',  'ASSISTANT',      NULL, 1),
 (2,  'Олена',   'Коваленко', 'lect2@lnu.edu.ua',  'SENIOR_LECTURER', 1,  2),
 (3,  'Петро',   'Шевченко',  'lect3@lnu.edu.ua',  'DOCENT',          2,  3),
 (4,  'Марія',   'Іванчук',   'lect4@lnu.edu.ua',  'PROFESSOR',       3,  4),
 (5,  'Андрій',  'Бондар',    'lect5@lnu.edu.ua',  'ASSISTANT',      NULL, 1),
 (6,  'Софія',   'Мельник',   'lect6@lnu.edu.ua',  'SENIOR_LECTURER', 1,  2),
 (7,  'Дмитро',  'Романюк',   'lect7@lnu.edu.ua',  'DOCENT',          2,  3),
 (8,  'Ірина',   'Ткаченко',  'lect8@lnu.edu.ua',  'PROFESSOR',       3,  4),
 (9,  'Тарас',   'Лисенко',   'lect9@lnu.edu.ua',  'ASSISTANT',      NULL, 1),
 (10, 'Наталія', 'Поліщук',   'lect10@lnu.edu.ua', 'SENIOR_LECTURER', 1,  2),
 (11, 'Іван',    'Кравець',   'lect11@lnu.edu.ua', 'DOCENT',          2,  3),
 (12, 'Олена',   'Гриценко',  'lect12@lnu.edu.ua', 'PROFESSOR',       3,  4),
 (13, 'Петро',   'Савчук',    'lect13@lnu.edu.ua', 'ASSISTANT',      NULL, 1),
 (14, 'Марія',   'Бойко',     'lect14@lnu.edu.ua', 'SENIOR_LECTURER', 1,  2),
 (15, 'Андрій',  'Марченко',  'lect15@lnu.edu.ua', 'DOCENT',          2,  3),
 (16, 'Софія',   'Гаврилюк',  'lect16@lnu.edu.ua', 'PROFESSOR',       3,  4),
 (17, 'Дмитро',  'Петренко',  'lect17@lnu.edu.ua', 'ASSISTANT',      NULL, 1),
 (18, 'Ірина',   'Коваленко', 'lect18@lnu.edu.ua', 'SENIOR_LECTURER', 1,  2),
 (19, 'Тарас',   'Шевченко',  'lect19@lnu.edu.ua', 'DOCENT',          2,  3),
 (20, 'Наталія', 'Іванчук',   'lect20@lnu.edu.ua', 'PROFESSOR',       3,  4),
 (21, 'Іван',    'Бондар',    'lect21@lnu.edu.ua', 'ASSISTANT',      NULL, 1),
 (22, 'Олена',   'Мельник',   'lect22@lnu.edu.ua', 'SENIOR_LECTURER', 1,  2),
 (23, 'Петро',   'Романюк',   'lect23@lnu.edu.ua', 'DOCENT',          2,  3),
 (24, 'Марія',   'Ткаченко',  'lect24@lnu.edu.ua', 'PROFESSOR',       3,  4),
 (25, 'Андрій',  'Лисенко',   'lect25@lnu.edu.ua', 'ASSISTANT',      NULL, 1),
 (26, 'Софія',   'Поліщук',   'lect26@lnu.edu.ua', 'SENIOR_LECTURER', 1,  2),
 (27, 'Дмитро',  'Кравець',   'lect27@lnu.edu.ua', 'DOCENT',          2,  3),
 (28, 'Ірина',   'Гриценко',  'lect28@lnu.edu.ua', 'PROFESSOR',       3,  4),
 (29, 'Тарас',   'Савчук',    'lect29@lnu.edu.ua', 'ASSISTANT',      NULL, 1),
 (30, 'Наталія', 'Бойко',     'lect30@lnu.edu.ua', 'SENIOR_LECTURER', 1,  2),
 (31, 'Іван',    'Марченко',  'lect31@lnu.edu.ua', 'DOCENT',          2,  3),
 (32, 'Олена',   'Гаврилюк',  'lect32@lnu.edu.ua', 'PROFESSOR',       3,  4),
 (33, 'Петро',   'Петренко',  'lect33@lnu.edu.ua', 'ASSISTANT',      NULL, 1),
 (34, 'Марія',   'Коваленко', 'lect34@lnu.edu.ua', 'SENIOR_LECTURER', 1,  2),
 (35, 'Андрій',  'Шевченко',  'lect35@lnu.edu.ua', 'DOCENT',          2,  3),
 (36, 'Софія',   'Іванчук',   'lect36@lnu.edu.ua', 'PROFESSOR',       3,  4),
 (37, 'Дмитро',  'Бондар',    'lect37@lnu.edu.ua', 'ASSISTANT',      NULL, 1),
 (38, 'Ірина',   'Мельник',   'lect38@lnu.edu.ua', 'SENIOR_LECTURER', 1,  2),
 (39, 'Тарас',   'Романюк',   'lect39@lnu.edu.ua', 'DOCENT',          2,  3),
 (40, 'Наталія', 'Ткаченко',  'lect40@lnu.edu.ua', 'PROFESSOR',       3,  4),
 (41, 'Іван',    'Лисенко',   'lect41@lnu.edu.ua', 'ASSISTANT',      NULL, 1),
 (42, 'Олена',   'Поліщук',   'lect42@lnu.edu.ua', 'SENIOR_LECTURER', 1,  2),
 (43, 'Петро',   'Кравець',   'lect43@lnu.edu.ua', 'DOCENT',          2,  3),
 (44, 'Марія',   'Гриценко',  'lect44@lnu.edu.ua', 'PROFESSOR',       3,  4),
 (45, 'Андрій',  'Савчук',    'lect45@lnu.edu.ua', 'ASSISTANT',      NULL, 1),
 (46, 'Софія',   'Бойко',     'lect46@lnu.edu.ua', 'SENIOR_LECTURER', 1,  2),
 (47, 'Дмитро',  'Марченко',  'lect47@lnu.edu.ua', 'DOCENT',          2,  3),
 (48, 'Ірина',   'Гаврилюк',  'lect48@lnu.edu.ua', 'PROFESSOR',       3,  4),
 (49, 'Тарас',   'Петренко',  'lect49@lnu.edu.ua', 'ASSISTANT',      NULL, 1),
 (50, 'Наталія', 'Коваленко', 'lect50@lnu.edu.ua', 'SENIOR_LECTURER', 1,  2),
 (51, 'Іван',    'Шевченко',  'lect51@lnu.edu.ua', 'DOCENT',          2,  3),
 (52, 'Олена',   'Іванчук',   'lect52@lnu.edu.ua', 'PROFESSOR',       3,  4),
 (53, 'Петро',   'Бондар',    'lect53@lnu.edu.ua', 'ASSISTANT',      NULL, 1),
 (54, 'Марія',   'Мельник',   'lect54@lnu.edu.ua', 'SENIOR_LECTURER', 1,  2),
 (55, 'Андрій',  'Романюк',   'lect55@lnu.edu.ua', 'DOCENT',          2,  3),
 (56, 'Софія',   'Ткаченко',  'lect56@lnu.edu.ua', 'PROFESSOR',       3,  4),
 (57, 'Дмитро',  'Лисенко',   'lect57@lnu.edu.ua', 'ASSISTANT',      NULL, 1),
 (58, 'Ірина',   'Поліщук',   'lect58@lnu.edu.ua', 'SENIOR_LECTURER', 1,  2),
 (59, 'Тарас',   'Кравець',   'lect59@lnu.edu.ua', 'DOCENT',          2,  3),
 (60, 'Наталія', 'Гриценко',  'lect60@lnu.edu.ua', 'PROFESSOR',       3,  4);
SELECT setval('lecturers_id_seq', 60);
-- building_id: 6=Університетський корпус, 4=Драгоманова, 1=Грушевського
INSERT INTO rooms (id, number, capacity, kind, faculty_id, building_id) VALUES
 (1,  '100', 30,  'LECTURE_HALL',  1, 6),
 (2,  '101', 60,  'COMPUTER_LAB',  2, 4),
 (3,  '102', 90,  'SEMINAR_ROOM',  1, 1),
 (4,  '103', 120, 'LECTURE_HALL',  2, 6),
 (5,  '104', 30,  'COMPUTER_LAB',  1, 4),
 (6,  '105', 60,  'SEMINAR_ROOM',  2, 1),
 (7,  '106', 90,  'LECTURE_HALL',  1, 6),
 (8,  '107', 120, 'COMPUTER_LAB',  2, 4),
 (9,  '108', 30,  'SEMINAR_ROOM',  1, 1),
 (10, '109', 60,  'LECTURE_HALL',  2, 6),
 (11, '110', 90,  'COMPUTER_LAB',  1, 4),
 (12, '111', 120, 'SEMINAR_ROOM',  2, 1),
 (13, '112', 30,  'LECTURE_HALL',  1, 6),
 (14, '113', 60,  'COMPUTER_LAB',  2, 4),
 (15, '114', 90,  'SEMINAR_ROOM',  1, 1),
 (16, '115', 120, 'LECTURE_HALL',  2, 6),
 (17, '116', 30,  'COMPUTER_LAB',  1, 4),
 (18, '117', 60,  'SEMINAR_ROOM',  2, 1),
 (19, '118', 90,  'LECTURE_HALL',  1, 6),
 (20, '119', 120, 'COMPUTER_LAB',  2, 4);
SELECT setval('rooms_id_seq', 20);
INSERT INTO time_slots (id, ordinal, start_time, end_time) VALUES (1, 1, '08:30', '09:50'),
 (2, 2, '10:10', '11:30'),
 (3, 3, '11:50', '13:10'),
 (4, 4, '13:30', '14:50'),
 (5, 5, '15:05', '16:25'),
 (6, 6, '16:40', '18:00');
SELECT setval('time_slots_id_seq', 6);
INSERT INTO lecturer_workloads (id, lecturer_id, academic_group_id, combined_group_id, working_curriculum_item_id) VALUES
 (1,  34, 1,    NULL, 1),   -- lecture wci=1, group 1
 (2,  2,  30,   NULL, 2),   -- lab wci=2, group 30
 (3,  33, NULL, 1,    1),   -- lecture wci=1, combined=1
 (4,  13, NULL, 2,    3),   -- lecture wci=3, combined=2
 (5,  51, NULL, 3,    5),   -- lecture wci=5, combined=3
 (6,  32, NULL, 4,    7),   -- lecture wci=7, combined=4
 (7,  19, 25,   NULL, 4),   -- practical wci=4, group 25
 (8,  36, 10,   NULL, 6),   -- lab wci=6, group 10
 (9,  37, NULL, 5,    9),   -- lecture wci=9, combined=5
 (10, 15, 9,    NULL, 10),  -- lab wci=10, group 9
 (11, 42, NULL, 6,    11),  -- lecture wci=11, combined=6
 (12, 30, 10,   NULL, 12),  -- practical wci=12, group 10
 (13, 28, 11,   NULL, 13),  -- lecture wci=13, group 11
 (14, 14, 11,   NULL, 14),  -- lab wci=14, group 11
 (15, 22, 12,   NULL, 15),  -- lecture wci=15, group 12
 (16, 43, 12,   NULL, 16);  -- practical wci=16, group 12
SELECT setval('lecturer_workloads_id_seq', 16);
INSERT INTO timetable_entries (id, day_of_week, week_parity, workload_id, time_slot_id, room_id) VALUES
 (1,  1, 'WEEKLY',      1,  1, 1),
 (2,  1, 'WEEKLY',      2,  2, 2),
 (3,  2, 'WEEKLY',      3,  1, 3),
 (4,  2, 'WEEKLY',      4,  2, 4),
 (5,  3, 'WEEKLY',      5,  1, 5),
 (6,  3, 'WEEKLY',      6,  2, 6),
 (7,  4, 'WEEKLY',      7,  1, 7),
 (8,  4, 'WEEKLY',      8,  2, 8),
 (9,  5, 'WEEKLY',      9,  1, 9),
 (10, 5, 'WEEKLY',      10, 2, 10),
 (11, 1, 'NUMERATOR',   11, 3, 11),
 (12, 1, 'DENOMINATOR', 12, 3, 12),
 (13, 2, 'NUMERATOR',   13, 4, 13),
 (14, 2, 'DENOMINATOR', 14, 4, 14),
 (15, 3, 'NUMERATOR',   15, 5, 15),
 (16, 3, 'DENOMINATOR', 16, 5, 16);
SELECT setval('timetable_entries_id_seq', 16);