--
-- LNU timetable seed data
-- Generated by scripts/lnu_import/build_sql.py on 2026-07-26T13:11:22Z
-- Source: https://lnu.edu.ua/structure/faculties and the faculty sites.
-- All ids are assigned from 1; load after schema.sql.
--

SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET client_min_messages = warning;

-- global_properties
INSERT INTO public.global_properties (name, type, value) VALUES ('academic_hour_duration_minutes', 'INTEGER', '40');
INSERT INTO public.global_properties (name, type, value) VALUES ('semester_duration_weeks', 'INTEGER', '16');
INSERT INTO public.global_properties (name, type, value) VALUES ('current_semester_parity', 'ENUM', 'ODD');
INSERT INTO public.global_properties (name, type, value) VALUES ('default_class_duration_hours', 'INTEGER', '2');

-- academic_degrees
INSERT INTO public.academic_degrees (id, name, abbreviation, level) VALUES (1, 'Кандидат наук', 'к.н.', 1);
INSERT INTO public.academic_degrees (id, name, abbreviation, level) VALUES (2, 'Доктор філософії', 'PhD', 2);
INSERT INTO public.academic_degrees (id, name, abbreviation, level) VALUES (3, 'Доктор наук', 'д-р н.', 3);

-- buildings (2 rows)
INSERT INTO public.buildings (id, name, address, city, postal_code) VALUES (1, 'Корпус на вул. Університетська 1', 'вул. Університетська 1', 'Львів', '79000');
INSERT INTO public.buildings (id, name, address, city, postal_code) VALUES (2, 'Корпус на проспект Свободи, 18', 'проспект Свободи, 18', 'Львів', '79008');

-- faculties (3 rows)
INSERT INTO public.faculties (id, name, abbreviation, website, email, phone, building_id) VALUES (1, 'Факультет прикладної математики та інформатики', 'ФПМіІ', 'https://ami.lnu.edu.ua', 'ami@lnu.edu.ua', '(+38 032) 274-01-80; 239-41-86', 1);
INSERT INTO public.faculties (id, name, abbreviation, website, email, phone, building_id) VALUES (2, 'Механіко-математичний факультет', 'ММФ', 'https://new.mmf.lnu.edu.ua', 'dmmf@lnu.edu.ua', '(+38 032) 260-00-09; 239-41-74', 1);
INSERT INTO public.faculties (id, name, abbreviation, website, email, phone, building_id) VALUES (3, 'Економічний факультет', 'ЕкФ', 'https://econom.lnu.edu.ua', 'edean@lnu.edu.ua', '(+38 032) 239-41-68', 2);

-- departments (3 rows)
INSERT INTO public.departments (id, name, abbreviation, faculty_id, email, phone) VALUES (1, 'Кафедра дискретного аналізу та інтелектуальних систем', 'КДАІС', 1, 'kdais@lnu.edu.ua', '(032) 239-42-11');
INSERT INTO public.departments (id, name, abbreviation, faculty_id, email, phone) VALUES (2, 'Кафедра програмування', 'КП', 1, 'programming.dep.ami@lnu.edu.ua', '(032) 239-47-57');
INSERT INTO public.departments (id, name, abbreviation, faculty_id, email, phone) VALUES (3, 'Кафедра алгебри, топології та основ математики', 'КАТОМ', 2, 'algebra.dep@lnu.edu.ua', '(032) 239-41-74');

-- specialties (4 rows)
INSERT INTO public.specialties (id, code, name, degree, faculty_id) VALUES (1, '014.09', 'Середня освіта (Інформатика)', 'BACHELOR', 1);
INSERT INTO public.specialties (id, code, name, degree, faculty_id) VALUES (2, '113', 'Прикладна математика', 'BACHELOR', 1);
INSERT INTO public.specialties (id, code, name, degree, faculty_id) VALUES (3, '014', 'Середня освіта (інформатика)', 'MASTER', 1);
INSERT INTO public.specialties (id, code, name, degree, faculty_id) VALUES (4, '111', 'Математика', 'BACHELOR', 2);

-- lecturers (8 rows)
INSERT INTO public.lecturers (id, first_name, middle_name, last_name, email, "position", academic_degree_id, min_hours_per_week, max_hours_per_week, department_id) VALUES (1, 'Микола', 'Миколайович', 'Притула', 'mykola.prytula@lnu.edu.ua', 'HEAD_OF_DEPARTMENT', 3, NULL, NULL, 1);
INSERT INTO public.lecturers (id, first_name, middle_name, last_name, email, "position", academic_degree_id, min_hours_per_week, max_hours_per_week, department_id) VALUES (2, 'Галина', 'Андріївна', 'Квасниця', 'halyna.kvasnytsya@lnu.edu.ua', 'DOCENT', 1, NULL, NULL, 1);
INSERT INTO public.lecturers (id, first_name, middle_name, last_name, email, "position", academic_degree_id, min_hours_per_week, max_hours_per_week, department_id) VALUES (3, 'Тетяна', 'Ігорівна', 'Стойко', 'tetiana.stoyko@lnu.edu.ua', 'ASSISTANT', 2, NULL, NULL, 1);
INSERT INTO public.lecturers (id, first_name, middle_name, last_name, email, "position", academic_degree_id, min_hours_per_week, max_hours_per_week, department_id) VALUES (4, 'Сергій', 'Адамович', 'Ярошко', 'serhiy.yaroshko@lnu.edu.ua', 'HEAD_OF_DEPARTMENT', 1, NULL, NULL, 2);
INSERT INTO public.lecturers (id, first_name, middle_name, last_name, email, "position", academic_degree_id, min_hours_per_week, max_hours_per_week, department_id) VALUES (5, 'Святослав', 'Володимирович', 'Літинський', 'svyatoslav.litynskyy@lnu.edu.ua', 'DOCENT', 1, NULL, NULL, 2);
INSERT INTO public.lecturers (id, first_name, middle_name, last_name, email, "position", academic_degree_id, min_hours_per_week, max_hours_per_week, department_id) VALUES (6, 'Василь', 'Ярославович', 'Костів', 'vasyl.kostiv@lnu.edu.ua', 'SENIOR_LECTURER', NULL, NULL, NULL, 2);
INSERT INTO public.lecturers (id, first_name, middle_name, last_name, email, "position", academic_degree_id, min_hours_per_week, max_hours_per_week, department_id) VALUES (7, 'Володимир', 'Любомирович', 'Бридун', 'volodymyr.brydun@lnu.edu.ua', 'DOCENT', 1, NULL, NULL, 3);
INSERT INTO public.lecturers (id, first_name, middle_name, last_name, email, "position", academic_degree_id, min_hours_per_week, max_hours_per_week, department_id) VALUES (8, 'Катерина', 'Миколаївна', 'Максимик', 'kateryna.maksymyk@lnu.edu.ua', 'ASSISTANT', NULL, NULL, NULL, 3);

-- academic_groups (7 rows)
INSERT INTO public.academic_groups (id, name, course_year, study_form, students_count, specialty_id) VALUES (1, 'Мат-11', 1, 'FULL_TIME', NULL, 4);
INSERT INTO public.academic_groups (id, name, course_year, study_form, students_count, specialty_id) VALUES (2, 'ПМо-11', 1, 'FULL_TIME', NULL, 1);
INSERT INTO public.academic_groups (id, name, course_year, study_form, students_count, specialty_id) VALUES (3, 'ПМо-41', 4, 'FULL_TIME', NULL, 1);
INSERT INTO public.academic_groups (id, name, course_year, study_form, students_count, specialty_id) VALUES (4, 'ПМом-11', 1, 'FULL_TIME', NULL, 3);
INSERT INTO public.academic_groups (id, name, course_year, study_form, students_count, specialty_id) VALUES (5, 'ПМі-11', 1, 'FULL_TIME', NULL, 2);
INSERT INTO public.academic_groups (id, name, course_year, study_form, students_count, specialty_id) VALUES (6, 'ПМі-12', 1, 'FULL_TIME', NULL, 2);
INSERT INTO public.academic_groups (id, name, course_year, study_form, students_count, specialty_id) VALUES (7, 'ПМі-41', 4, 'FULL_TIME', NULL, 2);

-- courses (16 rows)
INSERT INTO public.courses (id, name, course_type, faculty_id, department_id, parent_course_id) VALUES (1, 'Алгебра та геометрія', 'MANDATORY', 1, 3, NULL);
INSERT INTO public.courses (id, name, course_type, faculty_id, department_id, parent_course_id) VALUES (2, 'Програмування', 'MANDATORY', 1, 2, NULL);
INSERT INTO public.courses (id, name, course_type, faculty_id, department_id, parent_course_id) VALUES (3, 'Методика навчання інформатики', 'MANDATORY', 1, 2, NULL);
INSERT INTO public.courses (id, name, course_type, faculty_id, department_id, parent_course_id) VALUES (4, 'ДВ', 'ELECTIVE_GROUP', 1, NULL, NULL);
INSERT INTO public.courses (id, name, course_type, faculty_id, department_id, parent_course_id) VALUES (5, 'Динамічні моделі та методи прийняття рішень', 'ELECTIVE', 1, 1, 4);
INSERT INTO public.courses (id, name, course_type, faculty_id, department_id, parent_course_id) VALUES (6, 'Моделювання економіко-екологічних процесів', 'ELECTIVE', 1, 1, 4);
INSERT INTO public.courses (id, name, course_type, faculty_id, department_id, parent_course_id) VALUES (7, 'Чисельні методи', 'MANDATORY', 1, 2, NULL);
INSERT INTO public.courses (id, name, course_type, faculty_id, department_id, parent_course_id) VALUES (8, 'Рівняння математичної фізики', 'MANDATORY', 1, 1, NULL);
INSERT INTO public.courses (id, name, course_type, faculty_id, department_id, parent_course_id) VALUES (9, 'ДВ', 'ELECTIVE_GROUP', 1, NULL, NULL);
INSERT INTO public.courses (id, name, course_type, faculty_id, department_id, parent_course_id) VALUES (10, 'Динамічні моделі та методи прийняття рішень', 'ELECTIVE', 1, 1, 9);
INSERT INTO public.courses (id, name, course_type, faculty_id, department_id, parent_course_id) VALUES (11, 'Моделювання економіко-екологічних процесів', 'ELECTIVE', 1, 1, 9);
INSERT INTO public.courses (id, name, course_type, faculty_id, department_id, parent_course_id) VALUES (12, 'Курсова робота', 'COURSE_WORK', 1, 2, NULL);
INSERT INTO public.courses (id, name, course_type, faculty_id, department_id, parent_course_id) VALUES (13, 'ДВ', 'ELECTIVE_GROUP', 1, NULL, NULL);
INSERT INTO public.courses (id, name, course_type, faculty_id, department_id, parent_course_id) VALUES (14, 'Динамічна теорія інформації', 'ELECTIVE', 1, 1, 13);
INSERT INTO public.courses (id, name, course_type, faculty_id, department_id, parent_course_id) VALUES (15, 'Моделі статистичного навчання', 'ELECTIVE', 1, 1, 13);
INSERT INTO public.courses (id, name, course_type, faculty_id, department_id, parent_course_id) VALUES (16, 'Лінійна алгебра', 'MANDATORY', 2, 3, NULL);

-- course_specialties (17 rows)
INSERT INTO public.course_specialties (course_id, specialty_id) VALUES (1, 1);
INSERT INTO public.course_specialties (course_id, specialty_id) VALUES (2, 1);
INSERT INTO public.course_specialties (course_id, specialty_id) VALUES (3, 1);
INSERT INTO public.course_specialties (course_id, specialty_id) VALUES (4, 1);
INSERT INTO public.course_specialties (course_id, specialty_id) VALUES (5, 1);
INSERT INTO public.course_specialties (course_id, specialty_id) VALUES (6, 1);
INSERT INTO public.course_specialties (course_id, specialty_id) VALUES (1, 2);
INSERT INTO public.course_specialties (course_id, specialty_id) VALUES (7, 2);
INSERT INTO public.course_specialties (course_id, specialty_id) VALUES (8, 2);
INSERT INTO public.course_specialties (course_id, specialty_id) VALUES (9, 2);
INSERT INTO public.course_specialties (course_id, specialty_id) VALUES (10, 2);
INSERT INTO public.course_specialties (course_id, specialty_id) VALUES (11, 2);
INSERT INTO public.course_specialties (course_id, specialty_id) VALUES (12, 3);
INSERT INTO public.course_specialties (course_id, specialty_id) VALUES (13, 3);
INSERT INTO public.course_specialties (course_id, specialty_id) VALUES (14, 3);
INSERT INTO public.course_specialties (course_id, specialty_id) VALUES (15, 3);
INSERT INTO public.course_specialties (course_id, specialty_id) VALUES (16, 4);

-- course_tags (6 rows)
INSERT INTO public.course_tags (id, course_id, tag) VALUES (1, 4, 'середня освіта (інформатика)');
INSERT INTO public.course_tags (id, course_id, tag) VALUES (2, 4, 'семестр 7');
INSERT INTO public.course_tags (id, course_id, tag) VALUES (3, 9, 'прикладна математика');
INSERT INTO public.course_tags (id, course_id, tag) VALUES (4, 9, 'семестр 7');
INSERT INTO public.course_tags (id, course_id, tag) VALUES (5, 13, 'середня освіта (інформатика)');
INSERT INTO public.course_tags (id, course_id, tag) VALUES (6, 13, 'семестр 2');

-- curriculum_items (11 rows)
INSERT INTO public.curriculum_items (id, semester, control_form, ects_credits, specialty_id, course_id) VALUES (1, 1, 'EXAM', 5, 1, 1);
INSERT INTO public.curriculum_items (id, semester, control_form, ects_credits, specialty_id, course_id) VALUES (2, 1, 'EXAM', 6, 1, 2);
INSERT INTO public.curriculum_items (id, semester, control_form, ects_credits, specialty_id, course_id) VALUES (3, 7, 'EXAM', 4, 1, 3);
INSERT INTO public.curriculum_items (id, semester, control_form, ects_credits, specialty_id, course_id) VALUES (4, 7, 'CREDIT', NULL, 1, 4);
INSERT INTO public.curriculum_items (id, semester, control_form, ects_credits, specialty_id, course_id) VALUES (5, 1, 'EXAM', 5, 2, 1);
INSERT INTO public.curriculum_items (id, semester, control_form, ects_credits, specialty_id, course_id) VALUES (6, 1, 'EXAM', 5, 2, 7);
INSERT INTO public.curriculum_items (id, semester, control_form, ects_credits, specialty_id, course_id) VALUES (7, 7, 'EXAM', 4, 2, 8);
INSERT INTO public.curriculum_items (id, semester, control_form, ects_credits, specialty_id, course_id) VALUES (8, 7, 'CREDIT', NULL, 2, 9);
INSERT INTO public.curriculum_items (id, semester, control_form, ects_credits, specialty_id, course_id) VALUES (9, 2, 'GRADED_CREDIT', 3, 3, 12);
INSERT INTO public.curriculum_items (id, semester, control_form, ects_credits, specialty_id, course_id) VALUES (10, 2, 'CREDIT', NULL, 3, 13);
INSERT INTO public.curriculum_items (id, semester, control_form, ects_credits, specialty_id, course_id) VALUES (11, 1, 'EXAM', 5, 4, 16);

-- curriculum_item_hours (20 rows)
INSERT INTO public.curriculum_item_hours (id, curriculum_item_id, hour_type, hours) VALUES (1, 1, 'LECTURE', 32);
INSERT INTO public.curriculum_item_hours (id, curriculum_item_id, hour_type, hours) VALUES (2, 1, 'PRACTICAL', 32);
INSERT INTO public.curriculum_item_hours (id, curriculum_item_id, hour_type, hours) VALUES (3, 2, 'LECTURE', 32);
INSERT INTO public.curriculum_item_hours (id, curriculum_item_id, hour_type, hours) VALUES (4, 2, 'LAB', 32);
INSERT INTO public.curriculum_item_hours (id, curriculum_item_id, hour_type, hours) VALUES (5, 3, 'LECTURE', 32);
INSERT INTO public.curriculum_item_hours (id, curriculum_item_id, hour_type, hours) VALUES (6, 3, 'PRACTICAL', 16);
INSERT INTO public.curriculum_item_hours (id, curriculum_item_id, hour_type, hours) VALUES (7, 4, 'LECTURE', 16);
INSERT INTO public.curriculum_item_hours (id, curriculum_item_id, hour_type, hours) VALUES (8, 4, 'PRACTICAL', 16);
INSERT INTO public.curriculum_item_hours (id, curriculum_item_id, hour_type, hours) VALUES (9, 5, 'LECTURE', 32);
INSERT INTO public.curriculum_item_hours (id, curriculum_item_id, hour_type, hours) VALUES (10, 5, 'PRACTICAL', 32);
INSERT INTO public.curriculum_item_hours (id, curriculum_item_id, hour_type, hours) VALUES (11, 6, 'LECTURE', 32);
INSERT INTO public.curriculum_item_hours (id, curriculum_item_id, hour_type, hours) VALUES (12, 6, 'LAB', 32);
INSERT INTO public.curriculum_item_hours (id, curriculum_item_id, hour_type, hours) VALUES (13, 7, 'LECTURE', 32);
INSERT INTO public.curriculum_item_hours (id, curriculum_item_id, hour_type, hours) VALUES (14, 7, 'PRACTICAL', 16);
INSERT INTO public.curriculum_item_hours (id, curriculum_item_id, hour_type, hours) VALUES (15, 8, 'LECTURE', 16);
INSERT INTO public.curriculum_item_hours (id, curriculum_item_id, hour_type, hours) VALUES (16, 8, 'PRACTICAL', 16);
INSERT INTO public.curriculum_item_hours (id, curriculum_item_id, hour_type, hours) VALUES (17, 10, 'LECTURE', 32);
INSERT INTO public.curriculum_item_hours (id, curriculum_item_id, hour_type, hours) VALUES (18, 10, 'LAB', 32);
INSERT INTO public.curriculum_item_hours (id, curriculum_item_id, hour_type, hours) VALUES (19, 11, 'LECTURE', 32);
INSERT INTO public.curriculum_item_hours (id, curriculum_item_id, hour_type, hours) VALUES (20, 11, 'PRACTICAL', 32);

-- working_curriculum_items (26 rows)
INSERT INTO public.working_curriculum_items (id, curriculum_item_hours_id, lecturer_count, teaching_format, department_id, course_id) VALUES (1, 1, 1, 'TOGETHER', 3, NULL);
INSERT INTO public.working_curriculum_items (id, curriculum_item_hours_id, lecturer_count, teaching_format, department_id, course_id) VALUES (2, 2, 2, 'SEPARATELY', 3, NULL);
INSERT INTO public.working_curriculum_items (id, curriculum_item_hours_id, lecturer_count, teaching_format, department_id, course_id) VALUES (3, 3, 1, 'TOGETHER', 2, NULL);
INSERT INTO public.working_curriculum_items (id, curriculum_item_hours_id, lecturer_count, teaching_format, department_id, course_id) VALUES (4, 4, 1, 'TOGETHER', 2, NULL);
INSERT INTO public.working_curriculum_items (id, curriculum_item_hours_id, lecturer_count, teaching_format, department_id, course_id) VALUES (5, 5, 1, 'TOGETHER', 2, NULL);
INSERT INTO public.working_curriculum_items (id, curriculum_item_hours_id, lecturer_count, teaching_format, department_id, course_id) VALUES (6, 6, 1, 'TOGETHER', 2, NULL);
INSERT INTO public.working_curriculum_items (id, curriculum_item_hours_id, lecturer_count, teaching_format, department_id, course_id) VALUES (7, 7, 1, 'TOGETHER', 1, 5);
INSERT INTO public.working_curriculum_items (id, curriculum_item_hours_id, lecturer_count, teaching_format, department_id, course_id) VALUES (8, 7, 1, 'TOGETHER', 1, 6);
INSERT INTO public.working_curriculum_items (id, curriculum_item_hours_id, lecturer_count, teaching_format, department_id, course_id) VALUES (9, 8, 2, 'SEPARATELY', 1, 5);
INSERT INTO public.working_curriculum_items (id, curriculum_item_hours_id, lecturer_count, teaching_format, department_id, course_id) VALUES (10, 8, 1, 'TOGETHER', 1, 6);
INSERT INTO public.working_curriculum_items (id, curriculum_item_hours_id, lecturer_count, teaching_format, department_id, course_id) VALUES (11, 9, 1, 'TOGETHER', 3, NULL);
INSERT INTO public.working_curriculum_items (id, curriculum_item_hours_id, lecturer_count, teaching_format, department_id, course_id) VALUES (12, 10, 2, 'SEPARATELY', 3, NULL);
INSERT INTO public.working_curriculum_items (id, curriculum_item_hours_id, lecturer_count, teaching_format, department_id, course_id) VALUES (13, 11, 1, 'TOGETHER', 2, NULL);
INSERT INTO public.working_curriculum_items (id, curriculum_item_hours_id, lecturer_count, teaching_format, department_id, course_id) VALUES (14, 12, 2, 'SEPARATELY', 2, NULL);
INSERT INTO public.working_curriculum_items (id, curriculum_item_hours_id, lecturer_count, teaching_format, department_id, course_id) VALUES (15, 13, 1, 'TOGETHER', 1, NULL);
INSERT INTO public.working_curriculum_items (id, curriculum_item_hours_id, lecturer_count, teaching_format, department_id, course_id) VALUES (16, 14, 1, 'TOGETHER', 1, NULL);
INSERT INTO public.working_curriculum_items (id, curriculum_item_hours_id, lecturer_count, teaching_format, department_id, course_id) VALUES (17, 15, 1, 'TOGETHER', 1, 10);
INSERT INTO public.working_curriculum_items (id, curriculum_item_hours_id, lecturer_count, teaching_format, department_id, course_id) VALUES (18, 15, 1, 'TOGETHER', 1, 11);
INSERT INTO public.working_curriculum_items (id, curriculum_item_hours_id, lecturer_count, teaching_format, department_id, course_id) VALUES (19, 16, 2, 'SEPARATELY', 1, 10);
INSERT INTO public.working_curriculum_items (id, curriculum_item_hours_id, lecturer_count, teaching_format, department_id, course_id) VALUES (20, 16, 1, 'TOGETHER', 1, 11);
INSERT INTO public.working_curriculum_items (id, curriculum_item_hours_id, lecturer_count, teaching_format, department_id, course_id) VALUES (21, 17, 1, 'TOGETHER', 1, 14);
INSERT INTO public.working_curriculum_items (id, curriculum_item_hours_id, lecturer_count, teaching_format, department_id, course_id) VALUES (22, 17, 1, 'TOGETHER', 1, 15);
INSERT INTO public.working_curriculum_items (id, curriculum_item_hours_id, lecturer_count, teaching_format, department_id, course_id) VALUES (23, 18, 1, 'TOGETHER', 1, 14);
INSERT INTO public.working_curriculum_items (id, curriculum_item_hours_id, lecturer_count, teaching_format, department_id, course_id) VALUES (24, 18, 1, 'TOGETHER', 1, 15);
INSERT INTO public.working_curriculum_items (id, curriculum_item_hours_id, lecturer_count, teaching_format, department_id, course_id) VALUES (25, 19, 1, 'TOGETHER', 3, NULL);
INSERT INTO public.working_curriculum_items (id, curriculum_item_hours_id, lecturer_count, teaching_format, department_id, course_id) VALUES (26, 20, 1, 'TOGETHER', 3, NULL);

-- working_curriculum_item_groups (26 rows)
INSERT INTO public.working_curriculum_item_groups (working_curriculum_item_id, academic_group_id) VALUES (1, 2);
INSERT INTO public.working_curriculum_item_groups (working_curriculum_item_id, academic_group_id) VALUES (2, 2);
INSERT INTO public.working_curriculum_item_groups (working_curriculum_item_id, academic_group_id) VALUES (3, 2);
INSERT INTO public.working_curriculum_item_groups (working_curriculum_item_id, academic_group_id) VALUES (4, 2);
INSERT INTO public.working_curriculum_item_groups (working_curriculum_item_id, academic_group_id) VALUES (5, 3);
INSERT INTO public.working_curriculum_item_groups (working_curriculum_item_id, academic_group_id) VALUES (6, 3);
INSERT INTO public.working_curriculum_item_groups (working_curriculum_item_id, academic_group_id) VALUES (7, 3);
INSERT INTO public.working_curriculum_item_groups (working_curriculum_item_id, academic_group_id) VALUES (9, 3);
INSERT INTO public.working_curriculum_item_groups (working_curriculum_item_id, academic_group_id) VALUES (11, 5);
INSERT INTO public.working_curriculum_item_groups (working_curriculum_item_id, academic_group_id) VALUES (11, 6);
INSERT INTO public.working_curriculum_item_groups (working_curriculum_item_id, academic_group_id) VALUES (12, 5);
INSERT INTO public.working_curriculum_item_groups (working_curriculum_item_id, academic_group_id) VALUES (12, 6);
INSERT INTO public.working_curriculum_item_groups (working_curriculum_item_id, academic_group_id) VALUES (13, 5);
INSERT INTO public.working_curriculum_item_groups (working_curriculum_item_id, academic_group_id) VALUES (13, 6);
INSERT INTO public.working_curriculum_item_groups (working_curriculum_item_id, academic_group_id) VALUES (14, 5);
INSERT INTO public.working_curriculum_item_groups (working_curriculum_item_id, academic_group_id) VALUES (14, 6);
INSERT INTO public.working_curriculum_item_groups (working_curriculum_item_id, academic_group_id) VALUES (15, 7);
INSERT INTO public.working_curriculum_item_groups (working_curriculum_item_id, academic_group_id) VALUES (16, 7);
INSERT INTO public.working_curriculum_item_groups (working_curriculum_item_id, academic_group_id) VALUES (17, 7);
INSERT INTO public.working_curriculum_item_groups (working_curriculum_item_id, academic_group_id) VALUES (18, 7);
INSERT INTO public.working_curriculum_item_groups (working_curriculum_item_id, academic_group_id) VALUES (19, 7);
INSERT INTO public.working_curriculum_item_groups (working_curriculum_item_id, academic_group_id) VALUES (21, 4);
INSERT INTO public.working_curriculum_item_groups (working_curriculum_item_id, academic_group_id) VALUES (22, 4);
INSERT INTO public.working_curriculum_item_groups (working_curriculum_item_id, academic_group_id) VALUES (23, 4);
INSERT INTO public.working_curriculum_item_groups (working_curriculum_item_id, academic_group_id) VALUES (25, 1);
INSERT INTO public.working_curriculum_item_groups (working_curriculum_item_id, academic_group_id) VALUES (26, 1);

-- combined_working_curriculum_items (6 rows)
INSERT INTO public.combined_working_curriculum_items (id) VALUES (1);
INSERT INTO public.combined_working_curriculum_items (id) VALUES (2);
INSERT INTO public.combined_working_curriculum_items (id) VALUES (3);
INSERT INTO public.combined_working_curriculum_items (id) VALUES (4);
INSERT INTO public.combined_working_curriculum_items (id) VALUES (5);
INSERT INTO public.combined_working_curriculum_items (id) VALUES (6);

-- combined_working_curriculum_item_members (12 rows)
INSERT INTO public.combined_working_curriculum_item_members (combined_working_curriculum_item_id, working_curriculum_item_id) VALUES (1, 1);
INSERT INTO public.combined_working_curriculum_item_members (combined_working_curriculum_item_id, working_curriculum_item_id) VALUES (1, 11);
INSERT INTO public.combined_working_curriculum_item_members (combined_working_curriculum_item_id, working_curriculum_item_id) VALUES (2, 2);
INSERT INTO public.combined_working_curriculum_item_members (combined_working_curriculum_item_id, working_curriculum_item_id) VALUES (2, 12);
INSERT INTO public.combined_working_curriculum_item_members (combined_working_curriculum_item_id, working_curriculum_item_id) VALUES (3, 7);
INSERT INTO public.combined_working_curriculum_item_members (combined_working_curriculum_item_id, working_curriculum_item_id) VALUES (3, 17);
INSERT INTO public.combined_working_curriculum_item_members (combined_working_curriculum_item_id, working_curriculum_item_id) VALUES (4, 9);
INSERT INTO public.combined_working_curriculum_item_members (combined_working_curriculum_item_id, working_curriculum_item_id) VALUES (4, 19);
INSERT INTO public.combined_working_curriculum_item_members (combined_working_curriculum_item_id, working_curriculum_item_id) VALUES (5, 8);
INSERT INTO public.combined_working_curriculum_item_members (combined_working_curriculum_item_id, working_curriculum_item_id) VALUES (5, 18);
INSERT INTO public.combined_working_curriculum_item_members (combined_working_curriculum_item_id, working_curriculum_item_id) VALUES (6, 10);
INSERT INTO public.combined_working_curriculum_item_members (combined_working_curriculum_item_id, working_curriculum_item_id) VALUES (6, 20);

-- lecturer_workloads (19 rows)
INSERT INTO public.lecturer_workloads (id, working_curriculum_item_id, combined_working_curriculum_item_id, duration_hours) VALUES (1, NULL, 1, 2);
INSERT INTO public.lecturer_workloads (id, working_curriculum_item_id, combined_working_curriculum_item_id, duration_hours) VALUES (2, NULL, 2, 2);
INSERT INTO public.lecturer_workloads (id, working_curriculum_item_id, combined_working_curriculum_item_id, duration_hours) VALUES (3, NULL, 3, 2);
INSERT INTO public.lecturer_workloads (id, working_curriculum_item_id, combined_working_curriculum_item_id, duration_hours) VALUES (4, NULL, 4, 2);
INSERT INTO public.lecturer_workloads (id, working_curriculum_item_id, combined_working_curriculum_item_id, duration_hours) VALUES (5, NULL, 5, 2);
INSERT INTO public.lecturer_workloads (id, working_curriculum_item_id, combined_working_curriculum_item_id, duration_hours) VALUES (6, 3, NULL, 2);
INSERT INTO public.lecturer_workloads (id, working_curriculum_item_id, combined_working_curriculum_item_id, duration_hours) VALUES (7, 4, NULL, 2);
INSERT INTO public.lecturer_workloads (id, working_curriculum_item_id, combined_working_curriculum_item_id, duration_hours) VALUES (8, 5, NULL, 2);
INSERT INTO public.lecturer_workloads (id, working_curriculum_item_id, combined_working_curriculum_item_id, duration_hours) VALUES (9, 6, NULL, 2);
INSERT INTO public.lecturer_workloads (id, working_curriculum_item_id, combined_working_curriculum_item_id, duration_hours) VALUES (10, 13, NULL, 2);
INSERT INTO public.lecturer_workloads (id, working_curriculum_item_id, combined_working_curriculum_item_id, duration_hours) VALUES (11, 14, NULL, 2);
INSERT INTO public.lecturer_workloads (id, working_curriculum_item_id, combined_working_curriculum_item_id, duration_hours) VALUES (12, 14, NULL, 2);
INSERT INTO public.lecturer_workloads (id, working_curriculum_item_id, combined_working_curriculum_item_id, duration_hours) VALUES (13, 15, NULL, 2);
INSERT INTO public.lecturer_workloads (id, working_curriculum_item_id, combined_working_curriculum_item_id, duration_hours) VALUES (14, 16, NULL, 2);
INSERT INTO public.lecturer_workloads (id, working_curriculum_item_id, combined_working_curriculum_item_id, duration_hours) VALUES (15, 21, NULL, 2);
INSERT INTO public.lecturer_workloads (id, working_curriculum_item_id, combined_working_curriculum_item_id, duration_hours) VALUES (16, 22, NULL, 2);
INSERT INTO public.lecturer_workloads (id, working_curriculum_item_id, combined_working_curriculum_item_id, duration_hours) VALUES (17, 23, NULL, 2);
INSERT INTO public.lecturer_workloads (id, working_curriculum_item_id, combined_working_curriculum_item_id, duration_hours) VALUES (18, 25, NULL, 2);
INSERT INTO public.lecturer_workloads (id, working_curriculum_item_id, combined_working_curriculum_item_id, duration_hours) VALUES (19, 26, NULL, 2);

-- lecturer_workload_lecturers (21 rows)
INSERT INTO public.lecturer_workload_lecturers (lecturer_workload_id, lecturer_id) VALUES (1, 7);
INSERT INTO public.lecturer_workload_lecturers (lecturer_workload_id, lecturer_id) VALUES (2, 7);
INSERT INTO public.lecturer_workload_lecturers (lecturer_workload_id, lecturer_id) VALUES (2, 8);
INSERT INTO public.lecturer_workload_lecturers (lecturer_workload_id, lecturer_id) VALUES (3, 1);
INSERT INTO public.lecturer_workload_lecturers (lecturer_workload_id, lecturer_id) VALUES (4, 1);
INSERT INTO public.lecturer_workload_lecturers (lecturer_workload_id, lecturer_id) VALUES (4, 2);
INSERT INTO public.lecturer_workload_lecturers (lecturer_workload_id, lecturer_id) VALUES (5, 1);
INSERT INTO public.lecturer_workload_lecturers (lecturer_workload_id, lecturer_id) VALUES (6, 4);
INSERT INTO public.lecturer_workload_lecturers (lecturer_workload_id, lecturer_id) VALUES (7, 6);
INSERT INTO public.lecturer_workload_lecturers (lecturer_workload_id, lecturer_id) VALUES (8, 4);
INSERT INTO public.lecturer_workload_lecturers (lecturer_workload_id, lecturer_id) VALUES (9, 6);
INSERT INTO public.lecturer_workload_lecturers (lecturer_workload_id, lecturer_id) VALUES (10, 5);
INSERT INTO public.lecturer_workload_lecturers (lecturer_workload_id, lecturer_id) VALUES (11, 5);
INSERT INTO public.lecturer_workload_lecturers (lecturer_workload_id, lecturer_id) VALUES (12, 6);
INSERT INTO public.lecturer_workload_lecturers (lecturer_workload_id, lecturer_id) VALUES (13, 2);
INSERT INTO public.lecturer_workload_lecturers (lecturer_workload_id, lecturer_id) VALUES (14, 3);
INSERT INTO public.lecturer_workload_lecturers (lecturer_workload_id, lecturer_id) VALUES (15, 1);
INSERT INTO public.lecturer_workload_lecturers (lecturer_workload_id, lecturer_id) VALUES (16, 2);
INSERT INTO public.lecturer_workload_lecturers (lecturer_workload_id, lecturer_id) VALUES (17, 3);
INSERT INTO public.lecturer_workload_lecturers (lecturer_workload_id, lecturer_id) VALUES (18, 7);
INSERT INTO public.lecturer_workload_lecturers (lecturer_workload_id, lecturer_id) VALUES (19, 8);

-- lecturer_workload_academic_groups (26 rows)
INSERT INTO public.lecturer_workload_academic_groups (lecturer_workload_id, academic_group_id) VALUES (1, 2);
INSERT INTO public.lecturer_workload_academic_groups (lecturer_workload_id, academic_group_id) VALUES (1, 5);
INSERT INTO public.lecturer_workload_academic_groups (lecturer_workload_id, academic_group_id) VALUES (1, 6);
INSERT INTO public.lecturer_workload_academic_groups (lecturer_workload_id, academic_group_id) VALUES (2, 2);
INSERT INTO public.lecturer_workload_academic_groups (lecturer_workload_id, academic_group_id) VALUES (2, 5);
INSERT INTO public.lecturer_workload_academic_groups (lecturer_workload_id, academic_group_id) VALUES (2, 6);
INSERT INTO public.lecturer_workload_academic_groups (lecturer_workload_id, academic_group_id) VALUES (3, 3);
INSERT INTO public.lecturer_workload_academic_groups (lecturer_workload_id, academic_group_id) VALUES (3, 7);
INSERT INTO public.lecturer_workload_academic_groups (lecturer_workload_id, academic_group_id) VALUES (4, 3);
INSERT INTO public.lecturer_workload_academic_groups (lecturer_workload_id, academic_group_id) VALUES (4, 7);
INSERT INTO public.lecturer_workload_academic_groups (lecturer_workload_id, academic_group_id) VALUES (5, 7);
INSERT INTO public.lecturer_workload_academic_groups (lecturer_workload_id, academic_group_id) VALUES (6, 2);
INSERT INTO public.lecturer_workload_academic_groups (lecturer_workload_id, academic_group_id) VALUES (7, 2);
INSERT INTO public.lecturer_workload_academic_groups (lecturer_workload_id, academic_group_id) VALUES (8, 3);
INSERT INTO public.lecturer_workload_academic_groups (lecturer_workload_id, academic_group_id) VALUES (9, 3);
INSERT INTO public.lecturer_workload_academic_groups (lecturer_workload_id, academic_group_id) VALUES (10, 5);
INSERT INTO public.lecturer_workload_academic_groups (lecturer_workload_id, academic_group_id) VALUES (10, 6);
INSERT INTO public.lecturer_workload_academic_groups (lecturer_workload_id, academic_group_id) VALUES (11, 5);
INSERT INTO public.lecturer_workload_academic_groups (lecturer_workload_id, academic_group_id) VALUES (12, 6);
INSERT INTO public.lecturer_workload_academic_groups (lecturer_workload_id, academic_group_id) VALUES (13, 7);
INSERT INTO public.lecturer_workload_academic_groups (lecturer_workload_id, academic_group_id) VALUES (14, 7);
INSERT INTO public.lecturer_workload_academic_groups (lecturer_workload_id, academic_group_id) VALUES (15, 4);
INSERT INTO public.lecturer_workload_academic_groups (lecturer_workload_id, academic_group_id) VALUES (16, 4);
INSERT INTO public.lecturer_workload_academic_groups (lecturer_workload_id, academic_group_id) VALUES (17, 4);
INSERT INTO public.lecturer_workload_academic_groups (lecturer_workload_id, academic_group_id) VALUES (18, 1);
INSERT INTO public.lecturer_workload_academic_groups (lecturer_workload_id, academic_group_id) VALUES (19, 1);

-- class_start_times (6 rows)
INSERT INTO public.class_start_times (id, ordinal, start_time) VALUES (1, 1, '08:30');
INSERT INTO public.class_start_times (id, ordinal, start_time) VALUES (2, 2, '10:10');
INSERT INTO public.class_start_times (id, ordinal, start_time) VALUES (3, 3, '11:50');
INSERT INTO public.class_start_times (id, ordinal, start_time) VALUES (4, 4, '13:30');
INSERT INTO public.class_start_times (id, ordinal, start_time) VALUES (5, 5, '15:05');
INSERT INTO public.class_start_times (id, ordinal, start_time) VALUES (6, 6, '16:40');

--
-- Seeded accounts (admin@lnu.edu.ua / Admin#2026,
-- dean.fpmi@lnu.edu.ua and o.melnyk@lnu.edu.ua / Temp#12345)
--
INSERT INTO public.groups (id, name, description) VALUES (1, 'Деканат ФПМіІ', 'Deans office staff of the Faculty of Applied Mathematics and Informatics');
INSERT INTO public.groups (id, name, description) VALUES (2, 'Завідувачі кафедр', 'Heads of department, university-wide');
INSERT INTO public.users (id, email, first_name, last_name, password_hash, must_change_password, is_active) VALUES (1, 'admin@lnu.edu.ua', 'Адміністратор', 'Системи', '$2b$10$aU2Ny.wmIvCtafhZ4S9Vz.m/JY8hlWi4XZfjrqKHVbNDSP8yDRD2e', false, true);
INSERT INTO public.users (id, email, first_name, last_name, password_hash, must_change_password, is_active) VALUES (2, 'dean.fpmi@lnu.edu.ua', 'Софія', 'Мельник', '$2b$10$EPun8nZjuzjdnDbi8akF/OQI16Qq7VgcoLyQizwv3IMu4dAko7At6', true, true);
INSERT INTO public.users (id, email, first_name, last_name, password_hash, must_change_password, is_active) VALUES (3, 'o.melnyk@lnu.edu.ua', 'Олена', 'Коваленко', '$2b$10$EPun8nZjuzjdnDbi8akF/OQI16Qq7VgcoLyQizwv3IMu4dAko7At6', true, true);
INSERT INTO public.user_groups (user_id, group_id) VALUES (2, 1);
INSERT INTO public.user_groups (user_id, group_id) VALUES (3, 2);
INSERT INTO public.permissions (id, grantee_type, user_id, group_id, resource_type, resource_id, granted_by) VALUES (1, 'USER', 1, NULL, 'GLOBAL', NULL, NULL);
INSERT INTO public.permissions (id, grantee_type, user_id, group_id, resource_type, resource_id, granted_by) VALUES (2, 'GROUP', NULL, 1, 'FACULTY', 1, 1);
INSERT INTO public.permissions (id, grantee_type, user_id, group_id, resource_type, resource_id, granted_by) VALUES (3, 'USER', 3, NULL, 'DEPARTMENT', 1, 1);

--
-- Sequences
--
SELECT pg_catalog.setval('public.academic_degrees_id_seq', 3, true);
SELECT pg_catalog.setval('public.buildings_id_seq', 2, true);
SELECT pg_catalog.setval('public.faculties_id_seq', 3, true);
SELECT pg_catalog.setval('public.departments_id_seq', 3, true);
SELECT pg_catalog.setval('public.specialties_id_seq', 4, true);
SELECT pg_catalog.setval('public.lecturers_id_seq', 8, true);
SELECT pg_catalog.setval('public.academic_groups_id_seq', 7, true);
SELECT pg_catalog.setval('public.combined_groups_id_seq', 1, false);
SELECT pg_catalog.setval('public.students_id_seq', 1, false);
SELECT pg_catalog.setval('public.courses_id_seq', 16, true);
SELECT pg_catalog.setval('public.course_tags_id_seq', 6, true);
SELECT pg_catalog.setval('public.curriculum_items_id_seq', 11, true);
SELECT pg_catalog.setval('public.curriculum_item_hours_id_seq', 20, true);
SELECT pg_catalog.setval('public.working_curriculum_items_id_seq', 26, true);
SELECT pg_catalog.setval('public.combined_working_curriculum_items_id_seq', 6, true);
SELECT pg_catalog.setval('public.lecturer_workloads_id_seq', 19, true);
SELECT pg_catalog.setval('public.rooms_id_seq', 1, false);
SELECT pg_catalog.setval('public.class_start_times_id_seq', 6, true);
SELECT pg_catalog.setval('public.timetable_entries_id_seq', 1, false);
SELECT pg_catalog.setval('public.users_id_seq', 3, true);
SELECT pg_catalog.setval('public.groups_id_seq', 2, true);
SELECT pg_catalog.setval('public.permissions_id_seq', 3, true);

-- End of generated data
